const STORE_KEY='gearCheckerData';
const LEGACY_KEYS=['gear-checker-data','gear_checker_data','gearChecker','gear-checker','gearcheck-data'];
const seed={version:2,cases:[
 {id:'vevor-medium',name:'Vevor Medium Case',icon:'icons/cases/vevor-medium-case.svg',active:true,notes:'Case mediu principal',gear:[]},
 {id:'audio-small',name:'Small Audio Case',icon:'icons/cases/small-audio-case.svg',active:true,notes:'Kit audio compact',gear:[]},
 {id:'large-active',name:'Large Case — Activ',icon:'icons/cases/large-case-active.svg',active:true,notes:'Case mare folosit',gear:[]},
 {id:'large-empty',name:'Large Case — Gol',icon:'icons/cases/large-case-empty.svg',active:false,notes:'Case mare de rezervă, momentan gol',gear:[]}
]};
let data=load(),current=null,filter='all',pendingPhoto=null;
const caseIcons=[['icons/cases/vevor-medium-case.svg','Vevor Medium'],['icons/cases/small-audio-case.svg','Small Audio'],['icons/cases/large-case-active.svg','Large Case — activ'],['icons/cases/large-case-empty.svg','Large Case — gol'],['icons/cases/camera-backpack.svg','Camera Backpack'],['icons/cases/light-trolley.svg','Light Trolley'],['icons/cases/cable-pouch.svg','Cable Pouch'],['icons/cases/car-trunk.svg','Car Trunk']];
for(const [value,label] of caseIcons){const o=document.createElement('option');o.value=value;o.textContent=label;editIcon.prepend(o)}
function uid(){return crypto.randomUUID?.()||Date.now()+'-'+Math.random().toString(16).slice(2)}
function knownCaseIcon(id,current){return({'vevor-medium':'icons/cases/vevor-medium-case.svg','audio-small':'icons/cases/small-audio-case.svg','large-active':'icons/cases/large-case-active.svg','large-empty':'icons/cases/large-case-empty.svg'}[id])||current||'🧳'}
function normalize(raw){let x=raw?.data||raw||{};let cases=Array.isArray(x.cases)?x.cases:Array.isArray(x.bags)?x.bags:null;if(!cases)return structuredClone(seed);return{version:2,cases:cases.map((c,i)=>({id:String(c.id||uid()),name:c.name||c.title||`Case ${i+1}`,icon:knownCaseIcon(String(c.id||''),c.icon),active:c.active!==false,notes:c.notes||'',gear:(c.gear||c.items||[]).map(g=>({id:String(g.id||uid()),name:g.name||g.title||'Echipament',category:g.category||'',icon:g.icon||'🎥',notes:g.notes||'',status:(g.status==='in'||g.checked===true||g.packed===true)?'in':'out'}))}))}}
function load(){for(const k of [STORE_KEY,...LEGACY_KEYS]){try{const raw=localStorage.getItem(k);if(raw){const n=normalize(JSON.parse(raw));localStorage.setItem(STORE_KEY,JSON.stringify(n));return n}}catch(e){}}return structuredClone(seed)}
function save(){localStorage.setItem(STORE_KEY,JSON.stringify(data));render()}
const dbp=new Promise((res,rej)=>{const q=indexedDB.open('gearCheckerMedia',1);q.onupgradeneeded=()=>q.result.createObjectStore('photos');q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)});
async function photoPut(id,file){const db=await dbp;return new Promise((res,rej)=>{const tx=db.transaction('photos','readwrite');tx.objectStore('photos').put(file,id);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function photoGet(id){const db=await dbp;return new Promise(res=>{const q=db.transaction('photos').objectStore('photos').get(id);q.onsuccess=()=>res(q.result);q.onerror=()=>res(null)})}
async function photoDel(id){const db=await dbp;db.transaction('photos','readwrite').objectStore('photos').delete(id)}
function stats(){let all=data.cases.flatMap(c=>c.gear),ins=all.filter(g=>g.status==='in').length;return{all:all.length,ins,pct:all.length?Math.round(ins/all.length*100):0}}
async function render(){const s=stats();summary.textContent=`${s.ins} din ${s.all} pregătite`;ring.textContent=s.pct+'%';ring.style.setProperty('--pct',s.pct+'%');caseGrid.innerHTML='';for(const c of data.cases){const n=c.gear.filter(g=>g.status==='in').length,b=document.createElement('button');b.className='case-card'+(c.active?'':' inactive');b.innerHTML=`<span class="icon">${iconMarkup(c.icon)}</span><span class="badge">${c.active?'ACTIV':'REZERVĂ'}</span><h4>${esc(c.name)}</h4><p>${n}/${c.gear.length} IN</p>`;const ph=await photoGet(c.id);if(ph){let im=document.createElement('img');im.className='thumb';im.src=URL.createObjectURL(ph);b.prepend(im)}b.onclick=()=>openCase(c.id);caseGrid.append(b)}if(current)renderCase()}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function iconMarkup(icon){return String(icon).startsWith('icons/')?`<img class="case-svg" src="${esc(icon)}" alt="">`:esc(icon)}
async function renderCase(){const c=data.cases.find(x=>x.id===current);if(!c)return show('dashboard');caseHead.innerHTML=`<div class="case-title"><span class="icon">${iconMarkup(c.icon)}</span><div><h2>${esc(c.name)}</h2><p>${esc(c.notes||'Fără notițe')}</p></div><button class="editMini">Editează</button></div>`;caseHead.querySelector('button').onclick=()=>edit('case',c.id);gearList.innerHTML='';let gs=c.gear.filter(g=>filter==='all'||g.status===filter);if(!gs.length)gearList.innerHTML='<p class="hint">Niciun echipament aici încă.</p>';for(const g of gs){const row=document.createElement('div');row.className='gear-row';row.innerHTML=`<button class="gear-icon">${iconMarkup(g.icon)}</button><div><h4>${esc(g.name)}</h4><p>${esc(g.category||g.notes||'Echipament')}</p></div><button class="io ${g.status==='in'?'in':''}" aria-label="${g.status==='in'?'IN':'OUT'}"><span>${g.status==='in'?'I':'O'}</span></button>`;const ph=await photoGet(g.id);if(ph)row.querySelector('.gear-icon').innerHTML=`<img src="${URL.createObjectURL(ph)}">`;row.querySelector('.gear-icon').onclick=()=>edit('gear',g.id);row.querySelector('.io').onclick=()=>{g.status=g.status==='in'?'out':'in';save();navigator.vibrate?.(12)};gearList.append(row)}}
function show(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id))}
function openCase(id){current=id;show('caseView');renderCase()}
function edit(type,id){let obj=type==='case'?data.cases.find(c=>c.id===id):data.cases.find(c=>c.id===current)?.gear.find(g=>g.id===id);editType.value=type;editId.value=id||'';editorTitle.textContent=id?'Editează':'Adaugă';editName.value=obj?.name||'';editCategory.value=obj?.category||'';editIcon.value=obj?.icon||(type==='case'?'🧳':'🎥');editActive.checked=obj?.active!==false;editNotes.value=obj?.notes||'';categoryLabel.hidden=type==='case';activeLabel.hidden=type==='gear';deleteBtn.hidden=!id;editPhoto.value='';photoPreview.hidden=true;pendingPhoto=null;if(id)photoGet(id).then(p=>{if(p){photoPreview.src=URL.createObjectURL(p);photoPreview.hidden=false}});editor.showModal()}
editPhoto.onchange=()=>{pendingPhoto=editPhoto.files[0];if(pendingPhoto){photoPreview.src=URL.createObjectURL(pendingPhoto);photoPreview.hidden=false}};
editForm.addEventListener('submit',async e=>{if(e.submitter?.value!=='save')return;e.preventDefault();let type=editType.value,id=editId.value||uid(),obj;if(type==='case'){obj=data.cases.find(c=>c.id===id);if(!obj){obj={id,gear:[]};data.cases.push(obj)}Object.assign(obj,{name:editName.value.trim(),icon:editIcon.value,active:editActive.checked,notes:editNotes.value.trim()})}else{let c=data.cases.find(c=>c.id===current);obj=c.gear.find(g=>g.id===id);if(!obj){obj={id,status:'out'};c.gear.push(obj)}Object.assign(obj,{name:editName.value.trim(),category:editCategory.value.trim(),icon:editIcon.value,notes:editNotes.value.trim()})}if(pendingPhoto)await photoPut(id,pendingPhoto);editor.close();save()});
deleteBtn.onclick=async()=>{let type=editType.value,id=editId.value;if(!confirm('Sigur vrei să ștergi?'))return;if(type==='case'){let c=data.cases.find(x=>x.id===id);for(const g of c.gear)await photoDel(g.id);data.cases=data.cases.filter(x=>x.id!==id);current=null;show('dashboard')}else{let c=data.cases.find(x=>x.id===current);c.gear=c.gear.filter(x=>x.id!==id)}await photoDel(id);editor.close();save()};
addCase.onclick=()=>edit('case');addGear.onclick=()=>edit('gear');backBtn.onclick=()=>{current=null;show('dashboard');render()};settingsBtn.onclick=()=>show('settings');settingsBack.onclick=()=>show('dashboard');document.querySelectorAll('.segmented button').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('.segmented button').forEach(x=>x.classList.toggle('selected',x===b));renderCase()});
exportBtn.onclick=()=>{let blob=new Blob([JSON.stringify({...data,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`gear-check-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
importFile.onchange=async()=>{try{data=normalize(JSON.parse(await importFile.files[0].text()));save();alert('Backup importat.')}catch(e){alert('Fișierul nu este un backup valid.')}};
resetChecks.onclick=()=>{if(confirm('Pui toate echipamentele pe OUT?')){data.cases.forEach(c=>c.gear.forEach(g=>g.status='out'));save()}};
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));render();
