let businessView='dashboard',lastBusinessQuote=null,selectedNativeOfferId='';
const OFFER_PRESETS=[
  ['w26e','Nuntă 2026 · Essential Film',2100,'Event'],['w26s','Nuntă 2026 · Signature Film',2500,'Event'],['w26x','Nuntă 2026 · Editorial Experience',2900,'Event'],
  ['w27e','Nuntă 2027 · Essential Film',2400,'Event'],['w27s','Nuntă 2027 · Signature Film',2900,'Event'],['w27x','Nuntă 2027 · Editorial Experience',3400,'Event'],
  ['c26short','Cununie 2026 · Short Film',800,'Event'],['c26e','Cununie 2026 · Essential Film',1900,'Event'],['c26s','Cununie 2026 · Signature Film',2300,'Event'],['c26x','Cununie 2026 · Editorial Experience',2700,'Event'],
  ['c27short','Cununie 2027 · Short Film',1000,'Event'],['c27e','Cununie 2027 · Essential Film',2100,'Event'],['c27s','Cununie 2027 · Signature Film',2500,'Event'],['c27x','Cununie 2027 · Editorial Experience',2900,'Event'],
  ['b26short','Botez 2026 · Short Film',800,'Event'],['b26e','Botez 2026 · Essential Film',1800,'Event'],['b26s','Botez 2026 · Signature Film',2200,'Event'],['b26x','Botez 2026 · Editorial Experience',2600,'Event'],
  ['b27short','Botez 2027 · Short Film',1000,'Event'],['b27e','Botez 2027 · Essential Film',2000,'Event'],['b27s','Botez 2027 · Signature Film',2400,'Event'],['b27x','Botez 2027 · Editorial Experience',2800,'Event'],
  ['private1','Eveniment privat / Serbare · Highlights',450,'Event'],['private2','Eveniment privat / Serbare · Event Story',750,'Event'],['private3','Eveniment privat / Serbare · Complete',1350,'Event'],
  ['unique-reel-simple','Proiect unic · Reel simplu',600,'Unique'],['unique-reel-premium','Proiect unic · Reel premium',800,'Unique'],['unique-ad-simple','Proiect unic · Reclamă 16:9 simplă',850,'Unique'],['unique-ad-premium','Proiect unic · Reclamă 16:9 premium',1100,'Unique'],['unique-extra-simple','Proiect unic · Reel extra simplu',300,'Unique'],['unique-extra-premium','Proiect unic · Reel extra premium',500,'Unique'],
  ['ret-post','Retainer · Postări / lună',800,'Retainer'],['ret-ai','Retainer · AI Content / lună',1700,'Retainer'],['ret-hybrid','Retainer · Hybrid / lună',2200,'Retainer'],['ret-premium','Retainer · Premium Filmat / lună',3000,'Retainer'],
  ['unique-day','Proiect unic · Zi filmare separată',400,'Unique'],['unique-ai-reel','Proiect unic · Reel AI',200,'Unique'],['unique-ai-ad','Proiect unic · Reclamă AI (de la)',550,'Unique'],
  ['music-performance','Clip muzical · Performance',900,'Unique'],['music-story','Clip muzical · Story',1500,'Unique'],['music-cinematic','Clip muzical · Cinematic',2400,'Unique'],
  ['ret-day','Retainer · Zi filmare extra',300,'Retainer'],['ret-reel-simple','Retainer · Reel extra simplu',150,'Retainer'],['ret-reel-premium','Retainer · Reel extra premium',250,'Retainer'],['ret-ad-simple','Retainer · Reclamă 16:9 simplă',650,'Retainer'],['ret-ad-premium','Retainer · Reclamă 16:9 premium',900,'Retainer'],['ret-ai-reel','Retainer · Reel AI extra',170,'Retainer'],['ret-ai-ad','Retainer · Reclamă AI (de la)',500,'Retainer'],
  ['private-reel1','Eveniment privat 2026 · Reel Highlight',450,'Event'],['private-reel2','Eveniment privat 2026 · Story Reels',550,'Event'],['private-reel3','Eveniment privat 2026 · Complete Reels',650,'Event'],
  ['serbare1','Serbare grădiniță 2026 · Highlights',450,'Event'],['serbare2','Serbare grădiniță 2026 · Event Story',750,'Event'],['serbare3','Serbare grădiniță 2026 · Complete Event',1350,'Event'],
  ['2f-m-lite','2fast_OP · Munte · Lite',1610,'2fast'],['2f-m-lite-flash','2fast_OP · Munte · Lite FLASH DEAL',1730,'2fast'],['2f-m-plus','2fast_OP · Munte · Plus',2130,'2fast'],['2f-m-silver','2fast_OP · Munte · Silver',2380,'2fast'],['2f-m-gold','2fast_OP · Munte · Gold',2690,'2fast'],['2f-m-platinum','2fast_OP · Munte · Platinum',3810,'2fast'],
  ['2f-o-reels','2fast_OP · Oraș · City Reels',750,'2fast'],['2f-o-reels-flash4','2fast_OP · Oraș · City Reels FLASH · 4 reels',600,'2fast'],['2f-o-reels-flash5','2fast_OP · Oraș · City Reels FLASH · 5 reels',700,'2fast'],['2f-o-basic','2fast_OP · Oraș · City Basic',1100,'2fast'],['2f-o-basic-flash','2fast_OP · Oraș · City Basic FLASH DEAL',1200,'2fast'],['2f-o-standard','2fast_OP · Oraș · City Standard',1650,'2fast'],
  ['custom','Custom · fără preț în ofertă',0,'Custom']
].map(([id,label,eur,context])=>({id,label,eur,context}));
const OFFER_EXTRAS={
  wedding26:[['Fast Delivery',1000],['Premium Audio Recording',200],['Dronă',300],['Wedding Preview / Teaser',500],['Extra Hour',150],['Social Media Reel',400],['Extra Documentary Length',500],['Trash The Dress / Save The Date',650]],
  wedding27:[['Fast Delivery',1000],['Premium Audio Recording',200],['Dronă',300],['Wedding Preview / Teaser',550],['Extra Hour',150],['Social Media Reel',400],['Extra Documentary Length',500],['Trash The Dress / Save The Date',750]],
  civil:[['Fast Delivery',1000],['Premium Audio Recording',200],['Dronă',300],['Preview / Teaser',550],['Extra Hour',150],['Social Media Reel',400],['Extra Documentary Length',500],['Save The Date',650]],
  baptism:[['Fast Delivery',1000],['Premium Audio Recording',200],['Dronă',300],['Baptism Preview / Teaser',550],['Extra Hour',150],['Social Media Reel',400],['Extra Documentary Length',500]],
  private:[['Oră suplimentară',150],['Minut highlights suplimentar',150],['Al doilea videograf',250],['Reel vertical suplimentar',150],['Fast Delivery',200]],
  unique:[['Zi filmare suplimentară',400],['Reel extra simplu',300],['Reel extra premium',500],['Rundă modificări simple',50]],
  retainer:[['Zi filmare extra',300],['Reel extra simplu',150],['Reel extra premium',250],['Reclamă 16:9 simplă',650],['Reclamă 16:9 premium',900],['Reel AI',170],['Rundă modificări simple',50]]
  ,twofastM:[['Overtime / oră',50],['Video 16:9 extra',380],['Reel extra',120],['50 fotografii',100]]
  ,twofastO:[['Overtime / oră',50],['Video 16:9 extra',350],['Reel extra',100],['50 fotografii',100]]
};
function extraGroup(id){if(/^w26/.test(id))return'wedding26';if(/^w27/.test(id))return'wedding27';if(/^c2/.test(id))return'civil';if(/^b2/.test(id))return'baptism';if(/^private|^serbare/.test(id))return'private';if(/^unique|^music/.test(id))return'unique';if(/^ret/.test(id))return'retainer';if(/^2f-m/.test(id))return'twofastM';if(/^2f-o/.test(id))return'twofastO';return''}
function offerExtras(id){const p=pricePresets().find(x=>x.id===id);return OFFER_EXTRAS[p?.extraKey||extraGroup(id)]||[]}
function defaultDeliverables(p){const id=p.id;
  if(/^(c|b)2[67]short$/.test(id))return'1 videograf · Highlights cinematic 2-4 min · Acoperire 2-3h · Livrare online 4K';
  if(/^[wcb]2[67]e$/.test(id))return`1 videograf · Highlights cinematic 2-4 min · Film documentar 20-30 min · Acoperire ${id[0]==='w'?'8-10h':'8h'} · Livrare online 4K`;
  if(/^[wcb]2[67]s$/.test(id))return`1 videograf + 1 asistent · Highlights cinematic 3-5 min · Film documentar 30-40 min · Reel · Acoperire ${id[0]==='w'?'12h':'10h'} · Livrare online 4K`;
  if(/^[wcb]2[67]x$/.test(id))return`2 videografi · Highlights cinematic 4-6 min · Film documentar 40-50 min · Dronă · Save the Date AI · Acoperire ${id[0]==='w'?'14h':'12h'} · Livrare online 4K`;
  const exact={
    private1:'1 videograf · Acoperire până la 2h · Highlights cinematic 1 min · Montaj, colorizare și editare audio · Livrare online 4K',
    private2:'1 videograf · Acoperire până la 3h · Highlights cinematic 2 min · Captare audio dedicată · Intro simplu · Livrare online 4K',
    private3:'1 videograf · Acoperire până la 4h · A doua cameră fixă · Reel aprox. 30 sec · Film extins cinematic 5 min · Captare audio dedicată · Intro personalizat · Livrare online 4K',
    'private-reel1':'1 videograf · Acoperire până la 2h · 1 Reel aprox. 30 sec · Montaj simplu · Colorizare + sunet · Livrare online 4K',
    'private-reel2':'1 videograf · Acoperire până la 2h · 2 Reels aprox. 30 sec · Montaj simplu · Colorizare + sunet · Livrare online 4K',
    'private-reel3':'1 videograf · Acoperire până la 2h · 3 Reels aprox. 30 sec · Montaj simplu · Colorizare + sunet · Livrare online 4K',
    serbare1:'1 videograf · Acoperire până la 2h · Highlights cinematic 1 min · Montaj, colorizare și editare audio · Livrare online 4K',
    serbare2:'1 videograf · Acoperire până la 3h · Highlights cinematic 2 min · Captare audio dedicată · Intro simplu · Livrare online 4K',
    serbare3:'1 videograf · Acoperire până la 4h · A doua cameră fixă · Reel vertical · Film extins cinematic 5 min · Captare audio dedicată · Intro personalizat · Livrare online 4K',
    'unique-reel-simple':'1 Reel filmat · Filmare + montaj simplu · Subtitrări clasice',
    'unique-reel-premium':'1 Reel filmat · Filmare + montaj premium · Finisaj avansat',
    'unique-ad-simple':'1 reclamă video 16:9, max. 1 min · Zi de filmare · Montaj simplu',
    'unique-ad-premium':'1 reclamă video 16:9, max. 1 min · Zi de filmare · AI, grafică animată, voice-over, tranziții și finisaj avansat',
    'unique-extra-simple':'1 Reel extra din aceeași zi de filmare · Montaj simplu · Subtitrări clasice',
    'unique-extra-premium':'1 Reel extra din aceeași zi de filmare · Montaj premium · AI, grafică animată, voice-over și tranziții',
    'unique-day':'1 zi completă de producție video cu echipament profesional',
    'unique-ai-reel':'1 Reel generat cu AI · Script · Subtitrări · Montaj finalizat',
    'unique-ai-ad':'1 reclamă generată cu AI · Complexitatea se estimează separat',
    'music-performance':'Concept simplu · 1 locație · 1 zi de filmare până la 6h · Montaj performance 2-4 min · Colorizare cinematică · Livrare 4K · 1 rundă de modificări',
    'music-story':'Concept creativ + structură narativă · Până la 2 locații · 1 zi de filmare până la 10h · Montaj 2-5 min · Colorizare și sound design · 1 teaser vertical · Livrare 4K · 2 runde de modificări',
    'music-cinematic':'Concept și tratament regizoral · Preproducție avansată · Până la 2 zile de filmare · Mai multe locații · Montaj cinematic 2-6 min · Colorizare și sound design premium · 2 teasere verticale · Livrare 4K · 2 runde de modificări',
    'ret-post':'12 postări static/carousel pe lună · Copywriting adaptat brandului · Hashtag-uri actualizate · 0 zile filmare',
    'ret-ai':'10 video AI/lună · Subtitrări · Scripturi, idei și structură · 0 zile filmare',
    'ret-hybrid':'5 video filmate + 5 video AI · 1 zi filmare/lună · Montaj premium, efecte și colorizare · Scripturi și structură',
    'ret-premium':'10 video filmate · 3 zile filmare/lună · Montaj premium, colorizare și efecte · Subtitrări premium · Scripturi, concept și idei',
    '2f-m-lite':'Producție · 1 video 16:9 · 3 reels · Max. 10h/zi · 1 rundă revizii',
    '2f-m-lite-flash':'Producție · 1 video 16:9 · 4 reels · 50 fotografii · Max. 10h/zi · Volum fix FLASH DEAL',
    '2f-m-plus':'Producție · 2 video 16:9 · 4 reels · Max. 10h/zi · 1 rundă revizii',
    '2f-m-silver':'Producție · 2 video 16:9 · 6 reels · Max. 10h/zi · 1 rundă revizii',
    '2f-m-gold':'Producție · 3 video 16:9 · 5 reels · Max. 10h/zi · 1 rundă revizii',
    '2f-m-platinum':'Producție · 5 video 16:9 · 8 reels · Max. 10h/zi · 1 rundă revizii',
    '2f-o-reels':'1 zi filmare, max. 10h · 4 reels cu edit complet · 1 rundă revizii',
    '2f-o-reels-flash4':'1 zi filmare, max. 10h · 4 reels · 40 fotografii · Volum fix FLASH DEAL',
    '2f-o-reels-flash5':'1 zi filmare, max. 10h · 5 reels · 40 fotografii · Volum fix FLASH DEAL',
    '2f-o-basic':'1 zi filmare, max. 10h · 1 video 16:9 · 4 reels · Edit complet · 1 rundă revizii',
    '2f-o-basic-flash':'1 zi filmare, max. 10h · 1 video 16:9 (1:30-1:45) · 4 reels · 50 fotografii · Volum fix FLASH DEAL',
    '2f-o-standard':'1 zi filmare, max. 10h · 2 video 16:9 · 6 reels · Edit complet · 1 rundă revizii'
  };return exact[id]||(/ret-/.test(id)?p.label.replace('Retainer · ',''):p.label.replace(/^[^·]+ · /,''));
}
function defaultFilmingHours(p){const id=p.id;if(/^(c|b)2[67]short$/.test(id))return 3;if(/^w2[67]e$/.test(id))return 10;if(/^w2[67]s$/.test(id))return 12;if(/^w2[67]x$/.test(id))return 14;if(/^[cb]2[67]e$/.test(id))return 8;if(/^[cb]2[67]s$/.test(id))return 10;if(/^[cb]2[67]x$/.test(id))return 12;if(/^(private1|private-reel1|private-reel2|private-reel3|serbare1)$/.test(id))return 2;if(/^(private2|serbare2)$/.test(id))return 3;if(/^(private3|serbare3)$/.test(id))return 4;if(id==='music-performance')return 6;if(id==='music-story')return 10;if(id==='music-cinematic')return 20;if(/^2f-m/.test(id))return 30;if(/^2f-o/.test(id))return 10;if(id==='ret-hybrid')return 10;if(id==='ret-premium')return 30;if(id==='ret-day'||id==='unique-day'||/^unique-(reel|ad)/.test(id))return 10;return 0}
function ensureBusiness(){
  state.business||={projects:[],settings:{}};state.business.projects||=[];const s=state.business.settings||={};
  Object.assign(s,{monthlyEur:s.monthlyEur??5000,reserveEur:s.reserveEur??10000,eurRon:s.eurRon??5,weeks:s.weeks??46,billableHours:s.billableHours??24,safety:s.safety??.10,handling:s.handling??.10,premium:s.premium??.15,annualExpenses:s.annualExpenses??71600,taxIncome:s.taxIncome??.10,cas:s.cas??.25,cass:s.cass??.10,minSalary:s.minSalary??4050,vatThreshold:s.vatThreshold??395000,vatRate:s.vatRate??.21,vatStatus:s.vatStatus??'Neplătitor TVA',advance:s.advance??.50,costKm:s.costKm??1.5,ownerHourlyEur:s.ownerHourlyEur??30,recommendedBuffer:s.recommendedBuffer??.15});state.business.settings=s;
  state.business.deletedPresetIds||=[];const makePreset=p=>({...p,category:offerCategory(p),family:offerFamily(p),deliverables:defaultDeliverables(p),filmingHours:defaultFilmingHours(p)});if(!Array.isArray(state.business.pricePresets))state.business.pricePresets=OFFER_PRESETS.map(makePreset);else{OFFER_PRESETS.forEach(p=>{if(!state.business.deletedPresetIds.includes(p.id)&&!state.business.pricePresets.some(x=>x.id===p.id))state.business.pricePresets.push(makePreset(p))});state.business.pricePresets.forEach(p=>{p.category??=offerCategory(p);p.family??=offerFamily(p);p.deliverables??=defaultDeliverables(p);p.filmingHours??=defaultFilmingHours(p)})}return state.business;
}
function money(n){return Math.round(Number(n)||0).toLocaleString('ro-RO')+' lei'}
function euro(n){return Math.round(Number(n)||0).toLocaleString('ro-RO')+' €'}
function dualMoney(n){const s=ensureBusiness().settings;return `${money(n)} (${euro(Number(n||0)/s.eurRon)})`}
function taxEstimate(revenue,s){const net=Math.max(0,revenue-s.annualExpenses),cas=net<s.minSalary*12?0:(net<s.minSalary*24?s.minSalary*12*s.cas:s.minSalary*24*s.cas),cass=Math.min(net,s.minSalary*72)*s.cass,income=Math.max(0,net-cas-cass)*s.taxIncome;return{cas,cass,income,total:cas+cass+income,cash:revenue-s.annualExpenses-cas-cass-income}}
function businessTarget(){const s=ensureBusiness().settings,wanted=(s.monthlyEur*12+s.reserveEur)*s.eurRon;let lo=0,hi=2000000;for(let i=0;i<50;i++){const m=(lo+hi)/2;if(taxEstimate(m,s).cash<wanted)lo=m;else hi=m}return hi}
function pricePresets(){return ensureBusiness().pricePresets}
function offerPreset(id){return pricePresets().find(x=>x.id===id)||pricePresets().at(-1)}
function offerCategory(p){return p.category||(p.context==='Event'?'Evenimente':p.context==='Unique'?'Proiecte unice':p.context==='Retainer'?'Retainere':p.context==='2fast'?'2fast_OP':'Personalizat')}
function offerFamily(p){if(p.family)return p.family;const id=p.id;if(/^w26/.test(id))return'Nuntă 2026';if(/^w27/.test(id))return'Nuntă 2027';if(/^c26/.test(id))return'Cununie 2026';if(/^c27/.test(id))return'Cununie 2027';if(/^b26/.test(id))return'Botez 2026';if(/^b27/.test(id))return'Botez 2027';if(/^private-reel/.test(id))return'Reels eveniment privat 2026';if(/^private/.test(id))return'Eveniment privat 2026';if(/^serbare/.test(id))return'Serbare grădiniță 2026';if(/^music-/.test(id))return'Clip muzical';if(/^2f-m/.test(id))return'Munte';if(/^2f-o/.test(id))return'Oraș';return offerCategory(p)}
function shortOfferLabel(p){return p.name||p.label.replace(/^2fast_OP · (Munte|Oraș) · /,'').replace(offerFamily(p)+' · ','').replace(/^Proiect unic · /,'').replace(/^Retainer · /,'').replace(/^Custom · /,'')}
function isMainOfferPreset(p){return offerCategory(p)!=='Retainere'||['ret-post','ret-ai','ret-hybrid','ret-premium'].includes(p.id)||p.mainOffer===true}
function calcQuote(v){
  const s=ensureBusiness().settings,hours=v.hours.reduce((a,b)=>a+Number(b||0),0),targetRate=businessTarget()/(s.weeks*s.billableHours),direct=Number(v.km||0)*s.costKm+Number(v.direct||0),cost=direct*(1+s.handling),preset=offerPreset(v.offerId),baseOffer=Number(v.manualOffer||0)>0?Number(v.manualOffer):preset.eur,offer=(baseOffer+Number(v.offerExtras||0))*s.eurRon;
  const internalRate=(s.annualExpenses/(s.weeks*s.billableHours))+s.ownerHourlyEur*s.eurRon,internalFloor=(hours*internalRate+cost)*(1+s.safety),uplift=Number(v.risk||0)+Number(v.urgency||0)+Number(v.position||0)+Number(v.complexity||0),scopePrice=internalFloor*(1+s.recommendedBuffer+uplift),recommended=Math.max(offer,scopePrice),targetComplete=hours*targetRate*(1+s.safety+uplift)+cost;
  const selected=recommended,vat=s.vatStatus==='Plătitor TVA'?selected*s.vatRate:0,profit=selected-cost-hours*internalRate,margin=selected?profit/selected:0,effective=hours?selected/hours:0,targetContribution=targetComplete?selected/targetComplete:0;
  return{hours,targetRate,internalRate,direct,cost,offer,recommended,targetComplete,internalFloor,profit,margin,effective,targetContribution,vat,total:selected+vat,advance:(selected+vat)*s.advance,preset};
}
function bizNav(){return `<div class="biz-nav"><button class="${businessView==='dashboard'?'active':''}" onclick="businessView='dashboard';renderBusiness()">Dashboard</button><button class="${businessView==='offers'||businessView==='offer-detail'?'active':''}" onclick="businessView='offers';renderBusiness()">Ofertele mele</button><button class="${businessView==='calculator'?'active':''}" onclick="businessView='calculator';renderBusiness()">Calculator</button><button class="${businessView==='projects'?'active':''}" onclick="businessView='projects';renderBusiness()">Proiecte</button><button class="${businessView==='settings'?'active':''}" onclick="businessView='settings';renderBusiness()">Setări</button></div>`}
function renderBusiness(){ensureBusiness();title.textContent=businessView==='offers'||businessView==='offer-detail'?'Ofertele mele':'Business';if(businessView==='offers')return renderNativeOffers();if(businessView==='offer-detail')return renderNativeOfferDetail();if(businessView==='calculator')return renderBizCalculator();if(businessView==='projects')return renderBizProjects();if(businessView==='settings')return renderBizSettings();renderBizDashboard()}
function renderBizDashboard(){const b=ensureBusiness(),s=b.settings,target=businessTarget(),fact=b.projects.filter(p=>p.invoiced).reduce((a,p)=>a+Number(p.accepted||0),0),paid=b.projects.filter(p=>p.paid).reduce((a,p)=>a+Number(p.accepted||0),0),rate=target/(s.weeks*s.billableHours);view.innerHTML=bizNav()+`<section class="hero stack"><h2>Control business, fără estimări imposibile.</h2><p class="muted">Oferta publică, pragul intern și ținta completă sunt calculate separat.</p><button class="primary" onclick="openBusinessProjectForm()">＋ Calculează ofertă</button><button class="secondary" onclick="businessView='offers';renderBusiness()">Vezi toate ofertele</button></section><div class="grid two" style="margin-top:12px"><div class="card kpi"><span class="muted">Target anual</span><strong>${money(target)}</strong></div><div class="card kpi"><span class="muted">Tarif țintă/oră</span><strong>${money(rate)}</strong></div><div class="card kpi"><span class="muted">Facturat</span><strong>${money(fact)}</strong></div><div class="card kpi"><span class="muted">Încasat</span><strong>${money(paid)}</strong></div></div><div class="card flat stack" style="margin-top:12px"><div class="row"><b>Rămas până la target</b><b>${money(Math.max(0,target-fact))}</b></div><div class="progress"><div style="width:${Math.min(100,target?fact/target*100:0)}%"></div></div>${target>=s.vatThreshold?'<p class="biz-warning">Targetul depășește plafonul TVA configurat.</p>':''}</div>`}
function nativeOfferPrice(p){const rate=ensureBusiness().settings.eurRon;return p.eur?`${euro(p.eur)} · ${money(p.eur*rate)}`:'Preț personalizat'}
function renderNativeOffers(){const categories=[...new Set(pricePresets().map(offerCategory))];view.innerHTML=bizNav()+`<div class="offer-library-head"><div><p class="eyebrow">CTN VISUALS</p><h2>Ofertele mele</h2></div><button class="secondary tiny" onclick="openPricePresetManager()">Editează</button></div><label class="offer-search">Caută ofertă<input id="nativeOfferSearch" type="search" placeholder="Nuntă, serbare, clip muzical…" oninput="filterNativeOffers(this.value)"></label><div id="nativeOfferList">${categories.map((category,index)=>{const families=[...new Set(pricePresets().filter(p=>offerCategory(p)===category).map(offerFamily))];return`<details class="offer-category" ${index===0?'open':''}><summary><span>${escapeHtml(category)}</span><span class="pill">${pricePresets().filter(p=>offerCategory(p)===category).length}</span></summary>${families.map(family=>`<section class="offer-family"><h3>${escapeHtml(family)}</h3><div class="offer-card-grid">${pricePresets().filter(p=>offerCategory(p)===category&&offerFamily(p)===family).map(p=>`<button class="native-offer-card" data-search="${escapeHtml((category+' '+family+' '+shortOfferLabel(p)).toLowerCase())}" onclick="openNativeOffer('${p.id}')"><span><b>${escapeHtml(shortOfferLabel(p))}</b><small>${Number(p.filmingHours||0)}h filmare${isMainOfferPreset(p)?'':' · Extra'}</small></span><strong>${p.eur?euro(p.eur):'Custom'}</strong></button>`).join('')}</div></section>`).join('')}</details>`}).join('')}</div>`}
function filterNativeOffers(value){const query=String(value||'').trim().toLowerCase();document.querySelectorAll('.native-offer-card').forEach(card=>card.classList.toggle('hidden',query&&!card.dataset.search.includes(query)));document.querySelectorAll('.offer-category').forEach(group=>{const visible=[...group.querySelectorAll('.native-offer-card')].some(card=>!card.classList.contains('hidden'));group.classList.toggle('hidden',!visible);if(query&&visible)group.open=true})}
function openNativeOffer(id){selectedNativeOfferId=id;businessView='offer-detail';renderBusiness();window.scrollTo({top:0,behavior:'smooth'})}
function offerConditions(p){const category=offerCategory(p);if(category==='Evenimente')return['Data se rezervă prin contract și avans.','Orele suplimentare și extra-opțiunile se calculează separat.','Termenul final de livrare se stabilește în contract.'];if(category==='Retainere')return['Pachet lunar, cu livrabilele și zilele de filmare indicate.','Serviciile principale pot fi combinate.','Extra-opțiunile se adaugă separat.'];if(category==='2fast_OP')return['Programul de filmare și volumele sunt cele definite în preset.','Depășirea programului se taxează separat.','Modificările suplimentare se estimează separat.'];return['Oferta finală se confirmă după brief.','Costurile externe, locațiile și colaboratorii nu sunt incluse dacă nu sunt menționate.','Extra-opțiunile se adaugă separat.']}
function renderNativeOfferDetail(){const p=offerPreset(selectedNativeOfferId);if(!p){businessView='offers';return renderNativeOffers()}const extras=offerExtras(p.id),items=String(p.deliverables||'').split('·').map(x=>x.trim()).filter(Boolean);view.innerHTML=`<button class="ghost offer-back" onclick="businessView='offers';renderBusiness()">‹ Toate ofertele</button><article class="native-offer-detail"><p class="eyebrow">${escapeHtml(offerCategory(p))} · ${escapeHtml(offerFamily(p))}</p><h2>${escapeHtml(shortOfferLabel(p))}</h2><div class="offer-main-price">${nativeOfferPrice(p)}</div><div class="offer-hours">${Number(p.filmingHours||0)} ore de filmare incluse</div><section><h3>Include</h3><ul class="offer-check-list">${items.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></section>${extras.length?`<section><h3>Extra-opțiuni</h3><div class="offer-extra-list">${extras.map(([name,price])=>`<div><span>${escapeHtml(name)}</span><b>+ ${euro(price)}</b></div>`).join('')}</div></section>`:''}<section><h3>Condiții importante</h3><ul class="offer-condition-list">${offerConditions(p).map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></section><div class="stack"><button class="primary" onclick="useNativeOfferInCalculator('${p.id}')">Folosește în calculator</button><button class="secondary" onclick="openPricePresetForm('${p.id}')">Editează oferta</button></div></article>`}
function useNativeOfferInCalculator(id){const p=offerPreset(id);businessView='calculator';renderBusiness();qCategory.value=offerCategory(p);renderOfferFamilies(offerFamily(p),p.id)}
function defaultQuote(){return{name:'',offerId:'unique-ad-simple',deliverables:'',hours:[1,1.5,.75,1.5,4,1,6,1,1.5,1,1.5,.75],km:0,direct:0,manualOffer:0,offerExtras:0,risk:.1,urgency:0,position:0,complexity:.08}}
const hourLabels=['Brief / research','Preproducție','Pregătire echipament','Deplasare','Filmare','Backup / organizare','Editare montaj','Color','Sound design / muzică','Graphics / subtitrări','Revizii','Export / livrare'];
function openBusinessProjectForm(){businessView='calculator';renderBusiness()}
function renderBizCalculator(){const q=defaultQuote(),initial=offerPreset(q.offerId),category=offerCategory(initial),categories=[...new Set(pricePresets().map(offerCategory))];view.innerHTML=bizNav()+`<div class="card stack"><div class="row"><h2>Calculator ofertă</h2><button type="button" class="secondary tiny" onclick="openPricePresetManager()">Preseturi</button></div><label>Client / proiect<input id="qName" placeholder="Numele proiectului"></label><div class="offer-picker"><label>1. Categorie<select id="qCategory" onchange="renderOfferFamilies()">${categories.map(x=>`<option ${x===category?'selected':''}>${escapeHtml(x)}</option>`).join('')}</select></label><label id="qFamilyLabel">2. Tip ofertă<select id="qFamily" onchange="renderOfferPackages()"></select></label><label>3. Pachet / serviciu<select id="qOffer" onchange="renderOfferExtraChoices()"></select></label></div><label>Preț de ofertă introdus de tine (€)<input id="qManualOffer" type="number" min="0" value="0" placeholder="0 = folosește presetul"></label><p class="offer-hint">Dacă introduci o sumă aici, ea înlocuiește prețul presetului. Celelalte două calcule rămân independente.</p><div id="qExtraChoices"></div><label>Alte extra-uri manuale (€)<input id="qOfferExtras" type="number" min="0" value="0"></label><label>Livrabile incluse<textarea id="qDeliverables" readonly></textarea></label><p class="offer-hint">Livrabilele vin automat din preset. Le poți schimba din „Preseturi”.</p><h3>Timp real</h3><div class="hours-grid">${hourLabels.map((x,i)=>`<label>${x}<input class="qHour" type="number" min="0" step="0.25" value="${q.hours[i]}"></label>`).join('')}</div><h3>Costuri și context</h3><label>Kilometri dus + întors<input id="qKm" type="number" min="0" value="0"></label><label>Costuri directe / colaboratori (lei)<input id="qDirect" type="number" min="0" value="0"></label><label>Risc<select id="qRisk"><option value="0">Mic</option><option value=".1" selected>Mediu</option><option value=".2">Mare</option><option value=".3">Foarte mare</option></select></label><label>Urgență<select id="qUrgency"><option value="0">Normal</option><option value=".1">72h</option><option value=".2">48h</option><option value=".35">24h</option><option value=".5">Weekend / noapte</option></select></label><label>Poziționare<select id="qPosition"><option value="-.05">Client recurent</option><option value="0" selected>Standard</option><option value=".15">Premium</option><option value=".25">Brand / agenție mare</option><option value=".35">Campanie cu valoare mare</option></select></label><label>Complexitate<select id="qComplex"><option value="0">Simplu</option><option value=".08" selected>Normal</option><option value=".18">Complex</option><option value=".3">Foarte complex</option></select></label><button class="primary" onclick="calculateBusinessQuote()">Calculează</button></div><div id="quoteResult"></div>`;renderOfferFamilies(offerFamily(initial),q.offerId)}
function renderOfferFamilies(preferred='',preferredOffer=''){const available=pricePresets().filter(p=>offerCategory(p)===qCategory.value),families=[...new Set(available.map(offerFamily))],family= families.includes(preferred)?preferred:families[0];qFamily.innerHTML=families.map(x=>`<option ${x===family?'selected':''}>${escapeHtml(x)}</option>`).join('');qFamilyLabel.classList.toggle('hidden',families.length<=1);renderOfferPackages(preferredOffer)}
function renderOfferPackages(preferred=''){const available=pricePresets().filter(p=>offerCategory(p)===qCategory.value&&offerFamily(p)===qFamily.value&&isMainOfferPreset(p)),selected=available.some(p=>p.id===preferred)?preferred:available[0]?.id;qOffer.innerHTML=available.map(p=>`<option value="${p.id}" ${p.id===selected?'selected':''}>${escapeHtml(shortOfferLabel(p))} · ${p.eur?euro(p.eur):'prețul tău'}</option>`).join('');renderOfferExtraChoices()}
function extraHours(name){return /zi filmare/i.test(name)?10:/overtime|extra hour|oră suplimentară/i.test(name)?1:0}
function renderOfferExtraChoices(){const box=document.getElementById('qExtraChoices');if(!box)return;const preset=offerPreset(qOffer.value),extras=offerExtras(qOffer.value),monthly=offerCategory(preset)==='Retainere'?pricePresets().filter(p=>offerCategory(p)==='Retainere'&&isMainOfferPreset(p)&&p.id!==preset.id):[];box.innerHTML=`${monthly.length?`<p class="muted template-label">Completează abonamentul</p><p class="offer-hint">Poți combina pachetul ales cu încă unul sau cu toate.</p><div class="list">${monthly.map(p=>`<label class="item template-choice"><input type="checkbox" class="qBundleAddon" value="${p.id}" data-price="${p.eur}" onchange="updateQuoteComposition()"><span><b>${escapeHtml(shortOfferLabel(p))}</b><br><small class="muted">+ ${euro(p.eur)} · ${Number(p.filmingHours||0)}h filmare</small></span></label>`).join('')}</div>`:''}${extras.length?`<p class="muted template-label">Servicii extra</p><div class="list">${extras.map(([name,price])=>`<label class="item template-choice"><input type="checkbox" class="qPresetExtra" value="${price}" data-hours="${extraHours(name)}" onchange="updateQuoteComposition()"><span><b>${escapeHtml(name)}</b><br><small class="muted">${euro(price)}</small></span></label>`).join('')}</div>`:'<p class="offer-hint">Pentru acest preset poți introduce extra-uri manuale.</p>'}`;updateQuoteComposition()}
function updateQuoteComposition(){const base=offerPreset(qOffer.value),addons=[...document.querySelectorAll('.qBundleAddon:checked')].map(x=>offerPreset(x.value)),chosen=[base,...addons],deliverables=document.getElementById('qDeliverables'),filmInput=document.querySelectorAll('.qHour')[4],extraFilm=[...document.querySelectorAll('.qPresetExtra:checked')].reduce((a,x)=>a+Number(x.dataset.hours||0),0);if(deliverables)deliverables.value=chosen.map(p=>`${shortOfferLabel(p)}: ${p.deliverables||'Fără livrabile definite'}`).join('\n\n');if(filmInput)filmInput.value=chosen.reduce((a,p)=>a+Number(p.filmingHours||0),0)+extraFilm}
function openPricePresetManager(){const groups=[...new Set(pricePresets().map(offerCategory))];openModal('Preseturi de preț',`<div class="stack"><button type="button" class="primary" onclick="openPricePresetForm()">＋ Preset nou</button><p class="offer-hint">Fiecare preset păstrează categoria, tipul, prețul, orele de filmare și livrabilele. Modificările rămân în backup-ul aplicației.</p>${groups.map(group=>{const items=pricePresets().filter(p=>offerCategory(p)===group);return`<details class="template-details" ${group==='2fast_OP'?'open':''}><summary>${escapeHtml(group)} · ${items.length}</summary><div class="list">${items.map(p=>`<div class="item preset-admin-row"><div class="item-left"><div class="item-title">${escapeHtml(offerFamily(p))} · ${escapeHtml(shortOfferLabel(p))}</div><div class="item-sub">${p.eur?euro(p.eur):'Preț manual'} · ${Number(p.filmingHours||0)}h filmare · ${escapeHtml(p.deliverables||'Fără livrabile')}</div></div><div class="preset-admin-actions"><button type="button" class="secondary tiny" onclick="openPricePresetForm('${p.id}')">Editează</button><button type="button" class="ghost tiny" onclick="duplicatePricePreset('${p.id}')">Duplică</button><button type="button" class="danger tiny" onclick="deletePricePreset('${p.id}')">Șterge</button></div></div>`).join('')}</div></details>`}).join('')}</div>`)}
function openPricePresetForm(id=''){const source=id?offerPreset(id):{id:'',name:'',label:'',eur:0,category:'Personalizat',family:'Preseturile mele',deliverables:'',mainOffer:true,filmingHours:0},name=id?shortOfferLabel(source):'';openModal(id?'Editează preset':'Preset nou',`<div class="form-grid"><label>Categorie<input id="ppCategory" value="${escapeHtml(offerCategory(source))}" placeholder="Ex: Evenimente"></label><label>Tip / subcategorie<input id="ppFamily" value="${escapeHtml(offerFamily(source))}" placeholder="Ex: Nuntă 2027"></label><label>Numele pachetului<input id="ppName" value="${escapeHtml(name)}" placeholder="Ex: Signature Film"></label><label>Preț (€)<input id="ppPrice" type="number" min="0" value="${Number(source.eur||0)}"></label><label>Ore de filmare incluse<input id="ppFilmingHours" type="number" min="0" step="0.5" value="${Number(source.filmingHours||0)}"></label><label>Livrabile incluse<textarea id="ppDeliverables" placeholder="Scrie exact ce se livrează">${escapeHtml(source.deliverables||'')}</textarea></label><label class="item template-choice"><input id="ppMainOffer" type="checkbox" ${isMainOfferPreset(source)?'checked':''}><span><b>Apare în lista principală de pachete</b><br><small class="muted">Debifează pentru servicii extra.</small></span></label><div class="footer-actions"><button type="button" class="secondary" onclick="openPricePresetManager()">Înapoi</button><button type="button" class="primary" onclick="savePricePreset('${id}')">Salvează</button></div></div>`)}
function savePricePreset(id=''){const category=document.getElementById('ppCategory').value.trim(),family=document.getElementById('ppFamily').value.trim(),name=document.getElementById('ppName').value.trim(),eur=Number(document.getElementById('ppPrice').value),filmingHours=Number(document.getElementById('ppFilmingHours').value),deliverables=document.getElementById('ppDeliverables').value.trim(),mainOffer=document.getElementById('ppMainOffer').checked;if(!category||!family||!name)return alert('Completează categoria, tipul și numele pachetului.');const b=ensureBusiness(),existing=id?b.pricePresets.find(p=>p.id===id):null,label=category==='2fast_OP'?`${category} · ${family} · ${name}`:`${family} · ${name}`,data={id:id||`price-${uid()}`,name,label,eur,context:'Editable',category,family,deliverables,filmingHours,mainOffer};if(existing)Object.assign(existing,data);else b.pricePresets.push(data);save();openPricePresetManager()}
function duplicatePricePreset(id){const p=offerPreset(id),copy={...p,id:`price-${uid()}`,name:shortOfferLabel(p)+' — copie',label:p.label+' — copie',extraKey:p.extraKey||extraGroup(p.id)};ensureBusiness().pricePresets.push(copy);save();openPricePresetForm(copy.id)}
function deletePricePreset(id){const b=ensureBusiness(),p=b.pricePresets.find(x=>x.id===id);if(!p||!confirm(`Ștergi presetul „${shortOfferLabel(p)}”? Această acțiune nu poate fi anulată decât printr-un backup anterior.`))return;b.pricePresets=b.pricePresets.filter(x=>x.id!==id);if(OFFER_PRESETS.some(x=>x.id===id)&&!b.deletedPresetIds.includes(id))b.deletedPresetIds.push(id);save();openPricePresetManager()}
function quoteValues(){const preset=offerPreset(qOffer.value),presetExtras=[...document.querySelectorAll('.qPresetExtra:checked')].reduce((a,x)=>a+Number(x.value),0),bundleExtras=[...document.querySelectorAll('.qBundleAddon:checked')].reduce((a,x)=>a+Number(x.dataset.price||0),0);return{name:qName.value.trim(),offerId:qOffer.value,type:preset.label,deliverables:qDeliverables.value.trim(),hours:[...document.querySelectorAll('.qHour')].map(x=>Number(x.value)),km:Number(qKm.value),direct:Number(qDirect.value),manualOffer:Number(qManualOffer.value),offerExtras:presetExtras+bundleExtras+Number(qOfferExtras.value),risk:Number(qRisk.value),urgency:Number(qUrgency.value),position:Number(qPosition.value),complexity:Number(qComplex.value)}}
function profitabilityLabel(r){if(r.margin<0)return'Pierdere';if(r.margin<.15)return'Fragilă';if(r.margin<.30)return'Acceptabilă';if(r.margin<.45)return'Bună';return'Foarte bună'}
function calculateBusinessQuote(){const v=quoteValues(),r=calcQuote(v);lastBusinessQuote={v,r};quoteResult.innerHTML=`<div class="quote-results"><div class="quote minimum"><small>PREȚ DIN OFERTĂ</small><strong>${dualMoney(r.offer)}</strong></div><div class="quote recommended"><small>RECOMANDAT</small><strong>${dualMoney(r.recommended)}</strong></div><div class="quote premium"><small>ȚINTĂ COMPLETĂ</small><strong>${dualMoney(r.targetComplete)}</strong></div></div><div class="card flat stack"><div class="profit-grid"><div class="profit-metric"><small>Prag minim intern</small><b>${dualMoney(r.internalFloor)}</b></div><div class="profit-metric"><small>Profitabilitate</small><b>${profitabilityLabel(r)} · ${Math.round(r.margin*100)}%</b></div><div class="profit-metric"><small>Venit efectiv/oră</small><b>${dualMoney(r.effective)}</b></div><div class="profit-metric"><small>Acoperire țintă</small><b>${Math.round(r.targetContribution*100)}%</b></div></div><p class="offer-hint">${r.hours.toFixed(2)} ore · cost intern real ${dualMoney(r.internalRate)}/h · tarif pentru ținta completă ${dualMoney(r.targetRate)}/h</p><p>Total recomandat cu TVA: <b>${dualMoney(r.total)}</b> · Avans: <b>${dualMoney(r.advance)}</b></p><button class="primary" onclick="saveQuotedProject()">Salvează în Proiecte</button></div>`}
function saveQuotedProject(){const v=quoteValues(),r=calcQuote(v);if(!v.name)return alert('Pune numele proiectului.');ensureBusiness().projects.push({id:uid(),date:today(),name:v.name,type:v.type,deliverables:v.deliverables,offer:Math.round(r.offer),floor:Math.round(r.internalFloor),target:Math.round(r.targetComplete),quoted:Math.round(r.recommended),accepted:0,invoiced:false,paid:false,notes:''});save();businessView='projects';renderBusiness()}
function renderBizProjects(){const b=ensureBusiness();view.innerHTML=bizNav()+`<div class="row"><span class="pill">${b.projects.length} proiecte</span><button class="primary tiny" onclick="openBusinessProjectForm()">＋ Ofertă</button></div><div class="list" style="margin-top:12px">${b.projects.slice().reverse().map(p=>`<div class="card stack"><div class="row"><div><h2>${escapeHtml(p.name)}</h2><p class="muted">${p.date} · ${escapeHtml(p.type)}</p></div><span class="pill accent">${dualMoney(p.quoted)}</span></div>${p.offer!=null?`<p class="offer-hint">Ofertă ${dualMoney(p.offer)} · Prag ${dualMoney(p.floor)} · Țintă ${dualMoney(p.target)}</p>`:''}<label>Acceptat fără TVA (lei)<input type="number" value="${p.accepted||0}" onchange="updateBizProject('${p.id}','accepted',Number(this.value))"></label><div class="footer-actions"><button class="${p.invoiced?'primary':'secondary'}" onclick="updateBizProject('${p.id}','invoiced',!${p.invoiced})">${p.invoiced?'Facturat ✓':'Marchează facturat'}</button><button class="${p.paid?'primary':'secondary'}" onclick="updateBizProject('${p.id}','paid',!${p.paid})">${p.paid?'Încasat ✓':'Marchează încasat'}</button></div><button class="danger" onclick="deleteBizProject('${p.id}')">Șterge</button></div>`).join('')||empty('Nu ai proiecte salvate.')}</div>`}
function updateBizProject(id,k,v){const p=byId(ensureBusiness().projects,id);p[k]=v;save();renderBusiness()}
function deleteBizProject(id){if(confirm('Ștergi proiectul?')){state.business.projects=state.business.projects.filter(p=>p.id!==id);save();renderBusiness()}}
function renderBizSettings(){const s=ensureBusiness().settings;view.innerHTML=bizNav()+`<div class="card form-grid"><h2>Setări business</h2>${[['monthlyEur','Venit personal dorit / lună (€)'],['reserveEur','Rezervă anuală (€)'],['ownerHourlyEur','Valoarea minimă a muncii tale / oră (€)'],['recommendedBuffer','Buffer recomandare (ex: 0.15)'],['eurRon','Curs EUR/RON'],['weeks','Săptămâni active / an'],['billableHours','Ore facturabile / săptămână'],['annualExpenses','Cheltuieli deductibile anuale (lei)'],['vatThreshold','Plafon TVA (lei)'],['costKm','Cost / km (lei)']].map(([k,l])=>`<label>${l}<input id="bs_${k}" type="number" step="0.01" value="${s[k]}"></label>`).join('')}<label>Statut TVA<select id="bs_vatStatus"><option ${s.vatStatus==='Neplătitor TVA'?'selected':''}>Neplătitor TVA</option><option ${s.vatStatus==='Plătitor TVA'?'selected':''}>Plătitor TVA</option></select></label><button class="primary" onclick="saveBizSettings()">Salvează setările</button><p class="muted">Pragul minim folosește cheltuielile reale + valoarea muncii tale. Ținta completă păstrează modelul anterior cu venit dorit, rezervă și taxe.</p></div>`}
function saveBizSettings(){const s=ensureBusiness().settings;['monthlyEur','reserveEur','ownerHourlyEur','recommendedBuffer','eurRon','weeks','billableHours','annualExpenses','vatThreshold','costKm'].forEach(k=>s[k]=Number(document.getElementById('bs_'+k).value));s.vatStatus=bs_vatStatus.value;save();renderBusiness()}
