let businessView='dashboard';
function ensureBusiness(){
  state.business||={projects:[],settings:{monthlyEur:5000,reserveEur:10000,eurRon:5,weeks:46,billableHours:24,safety:0.10,handling:0.10,premium:0.15,annualExpenses:71600,taxIncome:0.10,cas:0.25,cass:0.10,minSalary:4050,vatThreshold:395000,vatRate:0.21,vatStatus:'Neplătitor TVA',advance:0.50,costKm:1.5}};
  state.business.projects||=[];return state.business;
}
function money(n){return Math.round(Number(n)||0).toLocaleString('ro-RO')+' lei'}
function taxEstimate(revenue,s){const net=Math.max(0,revenue-s.annualExpenses),cas=net<s.minSalary*12?0:(net<s.minSalary*24?s.minSalary*12*s.cas:s.minSalary*24*s.cas),cass=Math.min(net,s.minSalary*72)*s.cass,income=Math.max(0,net-cas-cass)*s.taxIncome;return{cas,cass,income,total:cas+cass+income,cash:revenue-s.annualExpenses-cas-cass-income}}
function businessTarget(){const s=ensureBusiness().settings,wanted=(s.monthlyEur*12+s.reserveEur)*s.eurRon;let lo=0,hi=2000000;for(let i=0;i<50;i++){const m=(lo+hi)/2;if(taxEstimate(m,s).cash<wanted)lo=m;else hi=m}return hi}
function calcQuote(v){const s=ensureBusiness().settings,hours=v.hours.reduce((a,b)=>a+Number(b||0),0),rate=businessTarget()/(s.weeks*s.billableHours),time=hours*rate,direct=Number(v.km||0)*s.costKm+Number(v.direct||0),cost=direct*(1+s.handling),uplift=Number(v.risk||0)+Number(v.urgency||0)+Number(v.position||0)+Number(v.complexity||0),min=time*(1+s.safety)+cost,recommended=time*(1+s.safety+uplift)+cost,premium=recommended*(1+s.premium),vat=s.vatStatus==='Plătitor TVA'?recommended*s.vatRate:0;return{hours,rate,time,direct,min,recommended,premium,vat,total:recommended+vat,advance:(recommended+vat)*s.advance}}
function bizNav(){return `<div class="biz-nav"><button class="${businessView==='dashboard'?'active':''}" onclick="businessView='dashboard';renderBusiness()">Dashboard</button><button class="${businessView==='calculator'?'active':''}" onclick="businessView='calculator';renderBusiness()">Ofertă</button><button class="${businessView==='projects'?'active':''}" onclick="businessView='projects';renderBusiness()">Proiecte</button><button class="${businessView==='settings'?'active':''}" onclick="businessView='settings';renderBusiness()">Setări</button></div>`}
function renderBusiness(){ensureBusiness();title.textContent='Business';if(businessView==='calculator')return renderBizCalculator();if(businessView==='projects')return renderBizProjects();if(businessView==='settings')return renderBizSettings();renderBizDashboard()}
function renderBizDashboard(){const b=ensureBusiness(),s=b.settings,target=businessTarget(),fact=b.projects.filter(p=>p.invoiced).reduce((a,p)=>a+Number(p.accepted||0),0),paid=b.projects.filter(p=>p.paid).reduce((a,p)=>a+Number(p.accepted||0),0),rate=target/(s.weeks*s.billableHours);view.innerHTML=bizNav()+`<section class="hero stack"><h2>Control business, fără Excel.</h2><p class="muted">Calculatorul și proiectele sunt salvate local și intră în backup.</p><button class="primary" onclick="openBusinessProjectForm()">＋ Calculează ofertă</button></section><div class="grid two" style="margin-top:12px"><div class="card kpi"><span class="muted">Target anual</span><strong>${money(target)}</strong></div><div class="card kpi"><span class="muted">Tarif intern/oră</span><strong>${money(rate)}</strong></div><div class="card kpi"><span class="muted">Facturat</span><strong>${money(fact)}</strong></div><div class="card kpi"><span class="muted">Încasat</span><strong>${money(paid)}</strong></div></div><div class="card flat stack" style="margin-top:12px"><div class="row"><b>Rămas până la target</b><b>${money(Math.max(0,target-fact))}</b></div><div class="progress"><div style="width:${Math.min(100,target?fact/target*100:0)}%"></div></div>${target>=s.vatThreshold?'<p class="biz-warning">Targetul depășește plafonul TVA configurat.</p>':''}</div>`}
function defaultQuote(){return{name:'',type:'Corporate',deliverables:'',hours:[1,1.5,.75,1.5,4,1,6,1,1.5,1,1.5,.75],km:0,direct:0,risk:.1,urgency:0,position:0,complexity:.08,budget:0}}
const hourLabels=['Brief / research','Preproducție','Pregătire echipament','Deplasare','Filmare','Backup / organizare','Editare montaj','Color','Sound design / muzică','Graphics / subtitrări','Revizii','Export / livrare'];
function openBusinessProjectForm(){businessView='calculator';renderBusiness()}
function renderBizCalculator(){const q=defaultQuote();view.innerHTML=bizNav()+`<div class="card stack"><h2>Calculator ofertă</h2><label>Client / proiect<input id="qName" placeholder="Numele proiectului"></label><label>Tip proiect<select id="qType">${['Reel / Social','Corporate','Product / Brand','Sport','Event','Real Estate','Restaurant / Hospitality','Wedding','Interviu / Podcast','Custom'].map(x=>`<option>${x}</option>`).join('')}</select></label><label>Livrabile<textarea id="qDeliverables" placeholder="1 brand film + 2 cutdowns"></textarea></label><h3>Timp real</h3><div class="hours-grid">${hourLabels.map((x,i)=>`<label>${x}<input class="qHour" type="number" min="0" step="0.25" value="${q.hours[i]}"></label>`).join('')}</div><h3>Costuri și context</h3><label>Kilometri dus + întors<input id="qKm" type="number" min="0" value="0"></label><label>Alte costuri directe<input id="qDirect" type="number" min="0" value="0"></label><label>Risc<select id="qRisk"><option value="0">Mic</option><option value=".1" selected>Mediu</option><option value=".2">Mare</option><option value=".3">Foarte mare</option></select></label><label>Urgență<select id="qUrgency"><option value="0">Normal</option><option value=".1">72h</option><option value=".2">48h</option><option value=".35">24h</option><option value=".5">Weekend / noapte</option></select></label><label>Poziționare<select id="qPosition"><option value="-.05">Client recurent</option><option value="0" selected>Standard</option><option value=".15">Premium</option><option value=".25">Brand / agenție mare</option><option value=".35">Campanie cu valoare mare</option></select></label><label>Complexitate<select id="qComplex"><option value="0">Simplu</option><option value=".08" selected>Normal</option><option value=".18">Complex</option><option value=".3">Foarte complex</option></select></label><button class="primary" onclick="calculateBusinessQuote()">Calculează</button></div><div id="quoteResult"></div>`}
function quoteValues(){return{name:qName.value.trim(),type:qType.value,deliverables:qDeliverables.value.trim(),hours:[...document.querySelectorAll('.qHour')].map(x=>Number(x.value)),km:Number(qKm.value),direct:Number(qDirect.value),risk:Number(qRisk.value),urgency:Number(qUrgency.value),position:Number(qPosition.value),complexity:Number(qComplex.value)}}
function calculateBusinessQuote(){const v=quoteValues(),r=calcQuote(v);quoteResult.innerHTML=`<div class="quote-results"><div class="quote minimum"><small>MINIM</small><strong>${money(r.min)}</strong></div><div class="quote recommended"><small>RECOMANDAT</small><strong>${money(r.recommended)}</strong></div><div class="quote premium"><small>PREMIUM</small><strong>${money(r.premium)}</strong></div></div><div class="card flat stack"><p>${r.hours.toFixed(2)} ore · tarif intern ${money(r.rate)}/h</p><p>Total cu TVA: <b>${money(r.total)}</b> · Avans: <b>${money(r.advance)}</b></p><button class="primary" onclick="saveQuotedProject()">Salvează în Proiecte</button></div>`}
function saveQuotedProject(){const v=quoteValues(),r=calcQuote(v);if(!v.name)return alert('Pune numele proiectului.');ensureBusiness().projects.push({id:uid(),date:today(),name:v.name,type:v.type,deliverables:v.deliverables,quoted:Math.round(r.recommended),accepted:0,invoiced:false,paid:false,notes:''});save();businessView='projects';renderBusiness()}
function renderBizProjects(){const b=ensureBusiness();view.innerHTML=bizNav()+`<div class="row"><span class="pill">${b.projects.length} proiecte</span><button class="primary tiny" onclick="openBusinessProjectForm()">＋ Ofertă</button></div><div class="list" style="margin-top:12px">${b.projects.slice().reverse().map(p=>`<div class="card stack"><div class="row"><div><h2>${escapeHtml(p.name)}</h2><p class="muted">${p.date} · ${escapeHtml(p.type)}</p></div><span class="pill accent">${money(p.quoted)}</span></div><label>Acceptat fără TVA<input type="number" value="${p.accepted||0}" onchange="updateBizProject('${p.id}','accepted',Number(this.value))"></label><div class="footer-actions"><button class="${p.invoiced?'primary':'secondary'}" onclick="updateBizProject('${p.id}','invoiced',!${p.invoiced})">${p.invoiced?'Facturat ✓':'Marchează facturat'}</button><button class="${p.paid?'primary':'secondary'}" onclick="updateBizProject('${p.id}','paid',!${p.paid})">${p.paid?'Încasat ✓':'Marchează încasat'}</button></div><button class="danger" onclick="deleteBizProject('${p.id}')">Șterge</button></div>`).join('')||empty('Nu ai proiecte salvate.')}</div>`}
function updateBizProject(id,k,v){const p=byId(ensureBusiness().projects,id);p[k]=v;save();renderBusiness()}function deleteBizProject(id){if(confirm('Ștergi proiectul?')){state.business.projects=state.business.projects.filter(p=>p.id!==id);save();renderBusiness()}}
function renderBizSettings(){const s=ensureBusiness().settings;view.innerHTML=bizNav()+`<div class="card form-grid"><h2>Setări business</h2>${[['monthlyEur','Venit personal dorit / lună (€)'],['reserveEur','Rezervă anuală (€)'],['eurRon','Curs EUR/RON'],['weeks','Săptămâni active / an'],['billableHours','Ore facturabile / săptămână'],['annualExpenses','Cheltuieli deductibile anuale (lei)'],['vatThreshold','Plafon TVA (lei)'],['costKm','Cost / km (lei)']].map(([k,l])=>`<label>${l}<input id="bs_${k}" type="number" step="0.01" value="${s[k]}"></label>`).join('')}<label>Statut TVA<select id="bs_vatStatus"><option ${s.vatStatus==='Neplătitor TVA'?'selected':''}>Neplătitor TVA</option><option ${s.vatStatus==='Plătitor TVA'?'selected':''}>Plătitor TVA</option></select></label><button class="primary" onclick="saveBizSettings()">Salvează setările</button><p class="muted">Estimare managerială, nu calcul fiscal final. Verifică anual taxele cu contabilul.</p></div>`}
function saveBizSettings(){const s=ensureBusiness().settings;['monthlyEur','reserveEur','eurRon','weeks','billableHours','annualExpenses','vatThreshold','costKm'].forEach(k=>s[k]=Number(document.getElementById('bs_'+k).value));s.vatStatus=bs_vatStatus.value;save();renderBusiness()}
