let businessView='dashboard',lastBusinessQuote=null;
const OFFER_PRESETS=[
  ['w26e','Nuntă 2026 · Essential Film',2100,'Event'],['w26s','Nuntă 2026 · Signature Film',2500,'Event'],['w26x','Nuntă 2026 · Editorial Experience',2900,'Event'],
  ['w27e','Nuntă 2027 · Essential Film',2400,'Event'],['w27s','Nuntă 2027 · Signature Film',2900,'Event'],['w27x','Nuntă 2027 · Editorial Experience',3400,'Event'],
  ['c26short','Cununie 2026 · Short Film',800,'Event'],['c26e','Cununie 2026 · Essential Film',1900,'Event'],['c26s','Cununie 2026 · Signature Film',2300,'Event'],['c26x','Cununie 2026 · Editorial Experience',2700,'Event'],
  ['c27short','Cununie 2027 · Short Film',1000,'Event'],['c27e','Cununie 2027 · Essential Film',2100,'Event'],['c27s','Cununie 2027 · Signature Film',2500,'Event'],['c27x','Cununie 2027 · Editorial Experience',2900,'Event'],
  ['b26short','Botez 2026 · Short Film',800,'Event'],['b26e','Botez 2026 · Essential Film',1800,'Event'],['b26s','Botez 2026 · Signature Film',2200,'Event'],['b26x','Botez 2026 · Editorial Experience',2600,'Event'],
  ['b27short','Botez 2027 · Short Film',1000,'Event'],['b27e','Botez 2027 · Essential Film',2000,'Event'],['b27s','Botez 2027 · Signature Film',2400,'Event'],['b27x','Botez 2027 · Editorial Experience',2800,'Event'],
  ['private1','Eveniment privat / Serbare · Highlights',450,'Event'],['private2','Eveniment privat / Serbare · Event Story',750,'Event'],['private3','Eveniment privat / Serbare · Complete',1350,'Event'],
  ['unique-reel-simple','Proiect unic · Reel simplu',600,'Unique'],['unique-reel-premium','Proiect unic · Reel premium',800,'Unique'],['unique-ad-simple','Proiect unic · Reclamă 16:9 simplă',850,'Unique'],['unique-ad-premium','Proiect unic · Reclamă 16:9 premium',1100,'Unique'],['unique-extra-simple','Proiect unic · Reel extra simplu',300,'Unique'],['unique-extra-premium','Proiect unic · Reel extra premium',500,'Unique'],
  ['ret-post','Retainer · Postări / lună',800,'Retainer'],['ret-ai','Retainer · AI Content / lună',1700,'Retainer'],['ret-hybrid','Retainer · Hybrid / lună',2200,'Retainer'],['ret-premium','Retainer · Premium Filmat / lună',3000,'Retainer'],
  ['unique-day','Proiect unic · Zi filmare separată',400,'Unique'],['unique-ai-reel','Proiect unic · Reel AI',200,'Unique'],['unique-ai-ad','Proiect unic · Reclamă AI (de la)',550,'Unique'],
  ['ret-day','Retainer · Zi filmare extra',300,'Retainer'],['ret-reel-simple','Retainer · Reel extra simplu',150,'Retainer'],['ret-reel-premium','Retainer · Reel extra premium',250,'Retainer'],['ret-ad-simple','Retainer · Reclamă 16:9 simplă',650,'Retainer'],['ret-ad-premium','Retainer · Reclamă 16:9 premium',900,'Retainer'],['ret-ai-reel','Retainer · Reel AI extra',170,'Retainer'],['ret-ai-ad','Retainer · Reclamă AI (de la)',500,'Retainer'],
  ['custom','Custom · fără preț în ofertă',0,'Custom']
].map(([id,label,eur,context])=>({id,label,eur,context}));
const OFFER_EXTRAS={
  wedding26:[['Fast Delivery',1000],['Premium Audio Recording',200],['Dronă',300],['Wedding Preview / Teaser',500],['Extra Hour',150],['Social Media Reel',400],['Extra Documentary Length',500],['Trash The Dress / Save The Date',650]],
  wedding27:[['Fast Delivery',1000],['Premium Audio Recording',200],['Dronă',300],['Wedding Preview / Teaser',550],['Extra Hour',150],['Social Media Reel',400],['Extra Documentary Length',500],['Trash The Dress / Save The Date',750]],
  civil:[['Fast Delivery',1000],['Premium Audio Recording',200],['Dronă',300],['Preview / Teaser',550],['Extra Hour',150],['Social Media Reel',400],['Extra Documentary Length',500],['Save The Date',650]],
  baptism:[['Fast Delivery',1000],['Premium Audio Recording',200],['Dronă',300],['Baptism Preview / Teaser',550],['Extra Hour',150],['Social Media Reel',400],['Extra Documentary Length',500]],
  private:[['Oră suplimentară',150],['Minut highlights suplimentar',150],['Al doilea videograf',250],['Reel vertical suplimentar',150],['Fast Delivery',200]],
  unique:[['Zi filmare suplimentară',400],['Reel extra simplu',300],['Reel extra premium',500],['Rundă modificări simple',50]],
  retainer:[['Zi filmare extra',300],['Reel extra simplu',150],['Reel extra premium',250],['Reclamă 16:9 simplă',650],['Reclamă 16:9 premium',900],['Reel AI',170],['Rundă modificări simple',50]]
};
function extraGroup(id){if(/^w26/.test(id))return'wedding26';if(/^w27/.test(id))return'wedding27';if(/^c2/.test(id))return'civil';if(/^b2/.test(id))return'baptism';if(/^private/.test(id))return'private';if(/^unique/.test(id))return'unique';if(/^ret/.test(id))return'retainer';return''}
function offerExtras(id){return OFFER_EXTRAS[extraGroup(id)]||[]}
function ensureBusiness(){
  state.business||={projects:[],settings:{}};state.business.projects||=[];const s=state.business.settings||={};
  Object.assign(s,{monthlyEur:s.monthlyEur??5000,reserveEur:s.reserveEur??10000,eurRon:s.eurRon??5,weeks:s.weeks??46,billableHours:s.billableHours??24,safety:s.safety??.10,handling:s.handling??.10,premium:s.premium??.15,annualExpenses:s.annualExpenses??71600,taxIncome:s.taxIncome??.10,cas:s.cas??.25,cass:s.cass??.10,minSalary:s.minSalary??4050,vatThreshold:s.vatThreshold??395000,vatRate:s.vatRate??.21,vatStatus:s.vatStatus??'Neplătitor TVA',advance:s.advance??.50,costKm:s.costKm??1.5,ownerHourlyEur:s.ownerHourlyEur??30,recommendedBuffer:s.recommendedBuffer??.15});state.business.settings=s;return state.business;
}
function money(n){return Math.round(Number(n)||0).toLocaleString('ro-RO')+' lei'}
function euro(n){return Math.round(Number(n)||0).toLocaleString('ro-RO')+' €'}
function taxEstimate(revenue,s){const net=Math.max(0,revenue-s.annualExpenses),cas=net<s.minSalary*12?0:(net<s.minSalary*24?s.minSalary*12*s.cas:s.minSalary*24*s.cas),cass=Math.min(net,s.minSalary*72)*s.cass,income=Math.max(0,net-cas-cass)*s.taxIncome;return{cas,cass,income,total:cas+cass+income,cash:revenue-s.annualExpenses-cas-cass-income}}
function businessTarget(){const s=ensureBusiness().settings,wanted=(s.monthlyEur*12+s.reserveEur)*s.eurRon;let lo=0,hi=2000000;for(let i=0;i<50;i++){const m=(lo+hi)/2;if(taxEstimate(m,s).cash<wanted)lo=m;else hi=m}return hi}
function offerPreset(id){return OFFER_PRESETS.find(x=>x.id===id)||OFFER_PRESETS.at(-1)}
function calcQuote(v){
  const s=ensureBusiness().settings,hours=v.hours.reduce((a,b)=>a+Number(b||0),0),targetRate=businessTarget()/(s.weeks*s.billableHours),direct=Number(v.km||0)*s.costKm+Number(v.direct||0),cost=direct*(1+s.handling),preset=offerPreset(v.offerId),baseOffer=Number(v.manualOffer||0)>0?Number(v.manualOffer):preset.eur,offer=(baseOffer+Number(v.offerExtras||0))*s.eurRon;
  const internalRate=(s.annualExpenses/(s.weeks*s.billableHours))+s.ownerHourlyEur*s.eurRon,internalFloor=(hours*internalRate+cost)*(1+s.safety),uplift=Number(v.risk||0)+Number(v.urgency||0)+Number(v.position||0)+Number(v.complexity||0),scopePrice=internalFloor*(1+s.recommendedBuffer+uplift),recommended=Math.max(offer,scopePrice),targetComplete=hours*targetRate*(1+s.safety+uplift)+cost;
  const selected=recommended,vat=s.vatStatus==='Plătitor TVA'?selected*s.vatRate:0,profit=selected-cost-hours*internalRate,margin=selected?profit/selected:0,effective=hours?selected/hours:0,targetContribution=targetComplete?selected/targetComplete:0;
  return{hours,targetRate,internalRate,direct,cost,offer,recommended,targetComplete,internalFloor,profit,margin,effective,targetContribution,vat,total:selected+vat,advance:(selected+vat)*s.advance,preset};
}
function bizNav(){return `<div class="biz-nav"><button class="${businessView==='dashboard'?'active':''}" onclick="businessView='dashboard';renderBusiness()">Dashboard</button><button class="${businessView==='calculator'?'active':''}" onclick="businessView='calculator';renderBusiness()">Ofertă</button><button class="${businessView==='projects'?'active':''}" onclick="businessView='projects';renderBusiness()">Proiecte</button><button class="${businessView==='settings'?'active':''}" onclick="businessView='settings';renderBusiness()">Setări</button></div>`}
function renderBusiness(){ensureBusiness();title.textContent='Business';if(businessView==='calculator')return renderBizCalculator();if(businessView==='projects')return renderBizProjects();if(businessView==='settings')return renderBizSettings();renderBizDashboard()}
function renderBizDashboard(){const b=ensureBusiness(),s=b.settings,target=businessTarget(),fact=b.projects.filter(p=>p.invoiced).reduce((a,p)=>a+Number(p.accepted||0),0),paid=b.projects.filter(p=>p.paid).reduce((a,p)=>a+Number(p.accepted||0),0),rate=target/(s.weeks*s.billableHours);view.innerHTML=bizNav()+`<section class="hero stack"><h2>Control business, fără estimări imposibile.</h2><p class="muted">Oferta publică, pragul intern și ținta completă sunt calculate separat.</p><button class="primary" onclick="openBusinessProjectForm()">＋ Calculează ofertă</button></section><div class="grid two" style="margin-top:12px"><div class="card kpi"><span class="muted">Target anual</span><strong>${money(target)}</strong></div><div class="card kpi"><span class="muted">Tarif țintă/oră</span><strong>${money(rate)}</strong></div><div class="card kpi"><span class="muted">Facturat</span><strong>${money(fact)}</strong></div><div class="card kpi"><span class="muted">Încasat</span><strong>${money(paid)}</strong></div></div><div class="card flat stack" style="margin-top:12px"><div class="row"><b>Rămas până la target</b><b>${money(Math.max(0,target-fact))}</b></div><div class="progress"><div style="width:${Math.min(100,target?fact/target*100:0)}%"></div></div>${target>=s.vatThreshold?'<p class="biz-warning">Targetul depășește plafonul TVA configurat.</p>':''}</div>`}
function defaultQuote(){return{name:'',offerId:'unique-ad-simple',deliverables:'',hours:[1,1.5,.75,1.5,4,1,6,1,1.5,1,1.5,.75],km:0,direct:0,manualOffer:0,offerExtras:0,risk:.1,urgency:0,position:0,complexity:.08}}
const hourLabels=['Brief / research','Preproducție','Pregătire echipament','Deplasare','Filmare','Backup / organizare','Editare montaj','Color','Sound design / muzică','Graphics / subtitrări','Revizii','Export / livrare'];
function openBusinessProjectForm(){businessView='calculator';renderBusiness()}
function renderBizCalculator(){const q=defaultQuote();view.innerHTML=bizNav()+`<div class="card stack"><h2>Calculator ofertă</h2><label>Client / proiect<input id="qName" placeholder="Numele proiectului"></label><label>Serviciu și ofertă<select id="qOffer" onchange="renderOfferExtraChoices()">${OFFER_PRESETS.map(x=>`<option value="${x.id}" ${x.id===q.offerId?'selected':''}>${escapeHtml(x.label)} · ${x.eur?euro(x.eur):'manual'}</option>`).join('')}</select></label><label>Preț de ofertă introdus de tine (€)<input id="qManualOffer" type="number" min="0" value="0" placeholder="0 = folosește presetul"></label><p class="offer-hint">Dacă introduci o sumă aici, ea înlocuiește prețul presetului. Celelalte două calcule rămân independente.</p><div id="qExtraChoices"></div><label>Alte extra-uri manuale (€)<input id="qOfferExtras" type="number" min="0" value="0"></label><label>Livrabile<textarea id="qDeliverables" placeholder="1 brand film + 2 cutdowns"></textarea></label><h3>Timp real</h3><div class="hours-grid">${hourLabels.map((x,i)=>`<label>${x}<input class="qHour" type="number" min="0" step="0.25" value="${q.hours[i]}"></label>`).join('')}</div><h3>Costuri și context</h3><label>Kilometri dus + întors<input id="qKm" type="number" min="0" value="0"></label><label>Costuri directe / colaboratori (lei)<input id="qDirect" type="number" min="0" value="0"></label><label>Risc<select id="qRisk"><option value="0">Mic</option><option value=".1" selected>Mediu</option><option value=".2">Mare</option><option value=".3">Foarte mare</option></select></label><label>Urgență<select id="qUrgency"><option value="0">Normal</option><option value=".1">72h</option><option value=".2">48h</option><option value=".35">24h</option><option value=".5">Weekend / noapte</option></select></label><label>Poziționare<select id="qPosition"><option value="-.05">Client recurent</option><option value="0" selected>Standard</option><option value=".15">Premium</option><option value=".25">Brand / agenție mare</option><option value=".35">Campanie cu valoare mare</option></select></label><label>Complexitate<select id="qComplex"><option value="0">Simplu</option><option value=".08" selected>Normal</option><option value=".18">Complex</option><option value=".3">Foarte complex</option></select></label><button class="primary" onclick="calculateBusinessQuote()">Calculează</button></div><div id="quoteResult"></div>`;renderOfferExtraChoices()}
function renderOfferExtraChoices(){const box=document.getElementById('qExtraChoices');if(!box)return;const extras=offerExtras(qOffer.value);box.innerHTML=extras.length?`<p class="muted template-label">Extra-opțiuni din oferta selectată</p><div class="list">${extras.map(([name,price],i)=>`<label class="item template-choice"><input type="checkbox" class="qPresetExtra" value="${price}"><span><b>${escapeHtml(name)}</b><br><small class="muted">${euro(price)}</small></span></label>`).join('')}</div>`:'<p class="offer-hint">Pentru Custom introduci direct prețul tău și orice extra manual.</p>'}
function quoteValues(){const preset=offerPreset(qOffer.value),presetExtras=[...document.querySelectorAll('.qPresetExtra:checked')].reduce((a,x)=>a+Number(x.value),0);return{name:qName.value.trim(),offerId:qOffer.value,type:preset.label,deliverables:qDeliverables.value.trim(),hours:[...document.querySelectorAll('.qHour')].map(x=>Number(x.value)),km:Number(qKm.value),direct:Number(qDirect.value),manualOffer:Number(qManualOffer.value),offerExtras:presetExtras+Number(qOfferExtras.value),risk:Number(qRisk.value),urgency:Number(qUrgency.value),position:Number(qPosition.value),complexity:Number(qComplex.value)}}
function profitabilityLabel(r){if(r.margin<0)return'Pierdere';if(r.margin<.15)return'Fragilă';if(r.margin<.30)return'Acceptabilă';if(r.margin<.45)return'Bună';return'Foarte bună'}
function calculateBusinessQuote(){const v=quoteValues(),r=calcQuote(v);lastBusinessQuote={v,r};quoteResult.innerHTML=`<div class="quote-results"><div class="quote minimum"><small>PREȚ DIN OFERTĂ</small><strong>${money(r.offer)}</strong></div><div class="quote recommended"><small>RECOMANDAT</small><strong>${money(r.recommended)}</strong></div><div class="quote premium"><small>ȚINTĂ COMPLETĂ</small><strong>${money(r.targetComplete)}</strong></div></div><div class="card flat stack"><div class="profit-grid"><div class="profit-metric"><small>Prag minim intern</small><b>${money(r.internalFloor)}</b></div><div class="profit-metric"><small>Profitabilitate</small><b>${profitabilityLabel(r)} · ${Math.round(r.margin*100)}%</b></div><div class="profit-metric"><small>Venit efectiv/oră</small><b>${money(r.effective)}</b></div><div class="profit-metric"><small>Acoperire țintă</small><b>${Math.round(r.targetContribution*100)}%</b></div></div><p class="offer-hint">${r.hours.toFixed(2)} ore · cost intern real ${money(r.internalRate)}/h · tarif pentru ținta completă ${money(r.targetRate)}/h</p><p>Total recomandat cu TVA: <b>${money(r.total)}</b> · Avans: <b>${money(r.advance)}</b></p><button class="primary" onclick="saveQuotedProject()">Salvează în Proiecte</button></div>`}
function saveQuotedProject(){const v=quoteValues(),r=calcQuote(v);if(!v.name)return alert('Pune numele proiectului.');ensureBusiness().projects.push({id:uid(),date:today(),name:v.name,type:v.type,deliverables:v.deliverables,offer:Math.round(r.offer),floor:Math.round(r.internalFloor),target:Math.round(r.targetComplete),quoted:Math.round(r.recommended),accepted:0,invoiced:false,paid:false,notes:''});save();businessView='projects';renderBusiness()}
function renderBizProjects(){const b=ensureBusiness();view.innerHTML=bizNav()+`<div class="row"><span class="pill">${b.projects.length} proiecte</span><button class="primary tiny" onclick="openBusinessProjectForm()">＋ Ofertă</button></div><div class="list" style="margin-top:12px">${b.projects.slice().reverse().map(p=>`<div class="card stack"><div class="row"><div><h2>${escapeHtml(p.name)}</h2><p class="muted">${p.date} · ${escapeHtml(p.type)}</p></div><span class="pill accent">${money(p.quoted)}</span></div>${p.offer!=null?`<p class="offer-hint">Ofertă ${money(p.offer)} · Prag ${money(p.floor)} · Țintă ${money(p.target)}</p>`:''}<label>Acceptat fără TVA<input type="number" value="${p.accepted||0}" onchange="updateBizProject('${p.id}','accepted',Number(this.value))"></label><div class="footer-actions"><button class="${p.invoiced?'primary':'secondary'}" onclick="updateBizProject('${p.id}','invoiced',!${p.invoiced})">${p.invoiced?'Facturat ✓':'Marchează facturat'}</button><button class="${p.paid?'primary':'secondary'}" onclick="updateBizProject('${p.id}','paid',!${p.paid})">${p.paid?'Încasat ✓':'Marchează încasat'}</button></div><button class="danger" onclick="deleteBizProject('${p.id}')">Șterge</button></div>`).join('')||empty('Nu ai proiecte salvate.')}</div>`}
function updateBizProject(id,k,v){const p=byId(ensureBusiness().projects,id);p[k]=v;save();renderBusiness()}
function deleteBizProject(id){if(confirm('Ștergi proiectul?')){state.business.projects=state.business.projects.filter(p=>p.id!==id);save();renderBusiness()}}
function renderBizSettings(){const s=ensureBusiness().settings;view.innerHTML=bizNav()+`<div class="card form-grid"><h2>Setări business</h2>${[['monthlyEur','Venit personal dorit / lună (€)'],['reserveEur','Rezervă anuală (€)'],['ownerHourlyEur','Valoarea minimă a muncii tale / oră (€)'],['recommendedBuffer','Buffer recomandare (ex: 0.15)'],['eurRon','Curs EUR/RON'],['weeks','Săptămâni active / an'],['billableHours','Ore facturabile / săptămână'],['annualExpenses','Cheltuieli deductibile anuale (lei)'],['vatThreshold','Plafon TVA (lei)'],['costKm','Cost / km (lei)']].map(([k,l])=>`<label>${l}<input id="bs_${k}" type="number" step="0.01" value="${s[k]}"></label>`).join('')}<label>Statut TVA<select id="bs_vatStatus"><option ${s.vatStatus==='Neplătitor TVA'?'selected':''}>Neplătitor TVA</option><option ${s.vatStatus==='Plătitor TVA'?'selected':''}>Plătitor TVA</option></select></label><button class="primary" onclick="saveBizSettings()">Salvează setările</button><p class="muted">Pragul minim folosește cheltuielile reale + valoarea muncii tale. Ținta completă păstrează modelul anterior cu venit dorit, rezervă și taxe.</p></div>`}
function saveBizSettings(){const s=ensureBusiness().settings;['monthlyEur','reserveEur','ownerHourlyEur','recommendedBuffer','eurRon','weeks','billableHours','annualExpenses','vatThreshold','costKm'].forEach(k=>s[k]=Number(document.getElementById('bs_'+k).value));s.vatStatus=bs_vatStatus.value;save();renderBusiness()}
