let shotView='projects',currentShotId=null;
const SHOT_CATEGORIES=['MUST HAVE','B-ROLL','PEOPLE','PRODUCT','DETAIL','CREATIVE','OPTIONAL'];
const shot=(text,category='B-ROLL',must=false)=>({id:uid(),text,category,must,checked:false});
function shotPreset(name,notes,groups){return{id:uid(),name,notes,items:Object.entries(groups).flatMap(([category,texts])=>texts.map(text=>shot(text,category,category==='MUST HAVE')))}}
function seedShotPresets(){
  const creative=['Slow Shutter','Whip pan transition','Low angle','Reflection / foreground','Rack focus'];
  return [
    shotPreset('Basketball — Home Game','Meci acasă · atmosferă, joc și reacții',{
      'MUST HAVE':['Establishing arena','Warm-up','Team entrance','Tip-off','Key offensive play','Key defensive play','Bench reactions','Final score','Win / defeat reaction'],
      'B-ROLL':['Exterior arena','Empty court','Crowd entrance','Scoreboard','Ball and net','Shoes on court','Jerseys','Sponsor branding','Arena lights'],
      'PEOPLE':['Coach','Players before game','Bench communication','Crowd reactions','Fans / family','Celebration'],
      'DETAIL':['Under basket slow-mo','Free throws','Three-point attempt','Fast break','Timeout / coach instructions'],
      'CREATIVE':creative,'OPTIONAL':['Mascot','Venue staff','Empty arena after game']
    }),
    shotPreset('Basketball — Away Game','Deplasare, vestiar, atmosferă și meci',{
      'MUST HAVE':['Team arrival','Locker room','Warm-up','Team entrance','Tip-off','Key plays','Bench reactions','Final score','Team leaving court'],
      'B-ROLL':['Road / arrival','Away arena exterior','Empty court','Scoreboard','Home crowd atmosphere'],
      'PEOPLE':['Coach talk','Player focus','Team huddle','Away supporters','Post-game reactions'],'CREATIVE':creative,'OPTIONAL':['Bus departure','Arena staff']
    }),
    shotPreset('Basketball — Training','Antrenament și conținut de echipă',{
      'MUST HAVE':['Arena establishing','Coach briefing','Team warm-up','Drills wide','Drills close','Team huddle'],
      'B-ROLL':['Ball rack','Shoes','Jerseys','Scoreboard','Court details'],'PEOPLE':['Coach portraits','Player portraits','Natural interaction'],'CREATIVE':creative,'OPTIONAL':['Behind the scenes']
    }),
    shotPreset('Basketball — Player Content','Portret individual și acțiune',{
      'MUST HAVE':['Clean player portrait','Front / side profile','Dribbling','Shot at basket','Signature move','Hero ending'],
      'DETAIL':['Hands on ball','Shoes','Jersey name / number','Face close-up'],'CREATIVE':creative,'OPTIONAL':['Smoke / practical light','Direct-to-camera']
    }),
    shotPreset('Real Estate','Exterior, flow, camere și detalii',{
      'MUST HAVE':['Exterior establishing','Entrance transition','Living room wide','Kitchen wide','Main bedroom','Bathroom','Balcony / view','Closing exterior'],
      'B-ROLL':['Hallway movement','Room transitions','Window view'],'DETAIL':['Finishes','Handles / fixtures','Lighting details','Branding'],'CREATIVE':creative,'OPTIONAL':['Agent on camera','Lifestyle action']
    }),
    shotPreset('Product','Hero, funcții, texturi și utilizare',{
      'MUST HAVE':['Clean hero shot','Front / back / sides','Product in use','Main feature','Logo / branding','Closing hero'],
      'PRODUCT':['Rotation','Interaction','Packaging','Scale reference'],'DETAIL':['Materials / texture','Buttons / ports','Macro detail'],'CREATIVE':creative,'OPTIONAL':['Smoke / atmosphere','Splash / particles']
    }),
    shotPreset('Corporate / Brand','Spațiu, oameni, proces și mesaj',{
      'MUST HAVE':['Company exterior','Workspace wide','Main activity','Team interaction','Hero service / product','Branding','Closing shot'],
      'B-ROLL':['Workflow','Hands working','Technology','Environment'],'PEOPLE':['Founder / spokesperson','Employee portraits','Natural reactions'],'DETAIL':['Logo','Tools','Product details'],'CREATIVE':creative,'OPTIONAL':['Drone / exterior movement']
    }),
    shotPreset('Interview','Interviu sigur + b-roll relevant',{
      'MUST HAVE':['A-camera framing','B-camera framing','Audio test','Room tone','Full interview','Safety ending statement'],
      'B-ROLL':['Subject working','Location wide','Relevant actions'],'PEOPLE':['Natural portrait','Hands / gestures','Listening reaction'],'DETAIL':['Microphone / environment detail'],'CREATIVE':creative,'OPTIONAL':['Walking interview']
    }),
    shotPreset('Restaurant / Hospitality','Locație, preparare, produs și atmosferă',{
      'MUST HAVE':['Exterior / signage','Interior wide','Signature preparation','Hero food / drink','Service moment','Guests atmosphere','Closing brand shot'],
      'B-ROLL':['Kitchen action','Table setup','Serving'],'PEOPLE':['Chef','Staff','Guest reactions'],'PRODUCT':['Signature dishes','Drinks'],'DETAIL':['Steam / texture','Cutlery','Branding'],'CREATIVE':creative,'OPTIONAL':['Empty venue beauty shots']
    }),
    shotPreset('Run & Gun','Listă universală pentru filmări rapide',{
      'MUST HAVE':['Location establishing','Main subject','Main action wide','Main action close','Clear ending'],'B-ROLL':['Environment','Movement','Transition shot'],'PEOPLE':['Natural reaction'],'DETAIL':['Relevant close-up'],'CREATIVE':creative,'OPTIONAL':['Behind the scenes']
    }),
    shotPreset('Eveniment privat','Atmosferă, oameni și momente importante',{
      'MUST HAVE':['Venue establishing','Guest arrival','Host / key people','Main moment','Speech / audio','Group reaction','Closing atmosphere'],
      'B-ROLL':['Decor','Food / drinks','Room atmosphere'],'PEOPLE':['Greetings','Natural reactions','Group interactions'],'DETAIL':['Invitations / branding','Table details'],'CREATIVE':creative,'OPTIONAL':['Guest messages']
    }),
    shotPreset('Nuntă','Momente irepetabile, audio și atmosferă',{
      'MUST HAVE':['Bride preparation','Groom preparation','Dress / rings','Ceremony entrance','Partner reaction','Vows / ceremony audio','Rings','Kiss','Ceremony exit','Couple session','Venue establishing','Reception entrance','First dance','Cake','Important speeches','Dance floor'],
      'B-ROLL':['Family preparation','Guests arriving','Decor','Room reveal'],'PEOPLE':['Parents reactions','Bridesmaids / groomsmen','Guest reactions'],'DETAIL':['Invitations','Accessories','Flowers','Table details'],'CREATIVE':creative,'OPTIONAL':['Drone','Private vows','After-party']
    }),
    shotPreset('Cununie','Ceremonie civilă și poveste compactă',{
      'MUST HAVE':['Location establishing','Couple arrival','Family arrivals','Ceremony opening','Signatures','Rings if present','Kiss','Exit / congratulations','Couple portraits'],
      'B-ROLL':['Location details','Guests','Reception atmosphere'],'PEOPLE':['Parents reactions','Friends reactions'],'DETAIL':['Documents','Flowers','Rings'],'CREATIVE':creative,'OPTIONAL':['Short messages']
    }),
    shotPreset('Botez','Pregătire, biserică, familie și petrecere',{
      'MUST HAVE':['Baby preparation','Family portraits','Church exterior','Church entrance','Ceremony key moments','Parents / godparents reactions','Exit','Venue establishing','Cake / key reception moment'],
      'B-ROLL':['Decor','Guests arriving','Reception atmosphere'],'PEOPLE':['Baby close-ups','Parents','Godparents','Grandparents'],'DETAIL':['Outfit','Candle','Church details','Table details'],'CREATIVE':creative,'OPTIONAL':['Family messages']
    }),
    shotPreset('Serbare','Scenă, copii, reacții și momente artistice',{
      'MUST HAVE':['Venue / stage establishing','Children entrance','Full stage safety shot','Every main performance','Teacher / host','Parents reactions','Finale / applause'],
      'B-ROLL':['Decor','Audience arriving','Backstage preparation'],'PEOPLE':['Children close-ups','Teacher reactions','Parents'],'DETAIL':['Costumes','Props','Program'],'CREATIVE':creative,'OPTIONAL':['Group messages']
    })
  ];
}
function ensureShotlists(){state.shotlists||={presets:[],projects:[]};state.shotlists.presets||=[];state.shotlists.projects||=[];if(!state.settings.shotPresetsV22){state.shotlists.presets.push(...seedShotPresets());state.settings.shotPresetsV22=true;save()}return state.shotlists}
function shotNav(){return `<div class="shot-nav"><button class="${shotView==='projects'?'active':''}" onclick="shotView='projects';currentShotId=null;renderShotlists()">Filmări</button><button class="${shotView==='presets'?'active':''}" onclick="shotView='presets';currentShotId=null;renderShotlists()">Preseturi</button></div>`}
function renderShotlists(){const d=ensureShotlists();title.textContent='Shotlist';if(currentShotId)return renderShotProject(currentShotId);document.body.classList.remove('shot-fullscreen');if(shotView==='presets')return renderShotPresets();view.innerHTML=shotNav()+`<button class="primary" onclick="openShotProjectForm()">＋ Proiect nou</button><div class="section-title"><h3>Active</h3></div>${shotProjectList(d.projects.filter(p=>!p.completed).reverse())}<div class="section-title"><h3>Finalizate</h3></div>${shotProjectList(d.projects.filter(p=>p.completed).reverse())}`}
function shotProjectList(projects){return projects.length?`<div class="list">${projects.map(p=>{const done=p.items.filter(i=>i.checked).length,must=p.items.filter(i=>i.must),mustDone=must.filter(i=>i.checked).length;return `<div class="item" onclick="currentShotId='${p.id}';renderShotlists()"><div class="item-left"><div class="item-title">${escapeHtml(p.name)}</div><div class="item-sub">${escapeHtml(p.date)} · ${done}/${p.items.length} cadre · MUST ${mustDone}/${must.length}</div></div><span class="pill ${p.completed?'ok':''}">${p.completed?'wrap ✓':Math.round(done/Math.max(1,p.items.length)*100)+'%'}</span></div>`}).join('')}</div>`:empty('Niciun shotlist aici momentan.')}
function renderShotPresets(){const d=ensureShotlists();view.innerHTML=shotNav()+`<button class="primary" onclick="openShotPresetForm()">＋ Preset nou</button><div class="grid" style="margin-top:12px">${d.presets.map(p=>`<div class="card stack"><div class="row"><div><h2>${escapeHtml(p.name)}</h2><p class="muted">${escapeHtml(p.notes||'')}</p></div><span class="pill accent">${p.items.length}</span></div><p class="charge-note">★ ${p.items.filter(i=>i.must).length} MUST HAVE</p><button class="secondary" onclick="openShotProjectForm('${p.id}')">Folosește presetul</button><div class="footer-actions"><button class="ghost" onclick="openShotPresetForm('${p.id}')">Editează</button><button class="danger" onclick="deleteShotPreset('${p.id}')">Șterge</button></div></div>`).join('')}</div>`}
function openShotProjectForm(presetId=''){const d=ensureShotlists();openModal('Proiect Shotlist',`<div class="form-grid"><label>Nume proiect<input id="spName" value="" placeholder="Rapid — Home Game"></label><label>Data<input id="spDate" type="date" value="${today()}"></label><label>Preset<select id="spPreset"><option value="">Shotlist gol</option>${d.presets.map(p=>`<option value="${p.id}" ${p.id===presetId?'selected':''}>${escapeHtml(p.name)}</option>`).join('')}</select></label><button type="button" class="primary" onclick="saveShotProject()">Creează proiect</button></div>`)}
function saveShotProject(){const d=ensureShotlists(),preset=byId(d.presets,spPreset.value),name=spName.value.trim()||preset?.name;if(!name)return alert('Pune numele proiectului.');const items=(preset?.items||[]).map(i=>({...i,id:uid(),checked:false}));const p={id:uid(),name,date:spDate.value||today(),presetId:preset?.id||'',items,started:false,completed:false,wrapItems:[]};d.projects.push(p);save();modal.close();shotView='projects';currentShotId=p.id;renderShotlists()}
function renderShotProject(id){const p=byId(ensureShotlists().projects,id);if(!p){currentShotId=null;return renderShotlists()}title.textContent=p.name;const done=p.items.filter(i=>i.checked).length,must=p.items.filter(i=>i.must),mustDone=must.filter(i=>i.checked).length;const cats=SHOT_CATEGORIES.filter(c=>p.items.some(i=>i.category===c));view.innerHTML=`<button class="ghost tiny" onclick="exitShootMode();currentShotId=null;renderShotlists()">‹ Înapoi</button><section class="card stack" style="margin-top:10px"><div class="row"><div><h2>${escapeHtml(p.name)}</h2><p class="muted">${escapeHtml(p.date)}</p></div><span class="pill ${p.completed?'ok':'accent'}">${p.completed?'WRAPPED':done+'/'+p.items.length}</span></div><div class="progress"><div style="width:${Math.round(done/Math.max(1,p.items.length)*100)}%"></div></div><div class="shot-summary"><div class="card flat kpi"><small class="muted">TOTAL</small><strong>${done}/${p.items.length}</strong></div><div class="card flat kpi"><small class="muted">MUST HAVE</small><strong>${mustDone}/${must.length}</strong></div></div><div class="footer-actions"><button class="${p.started?'secondary':'primary'}" onclick="startShoot('${p.id}')">${p.started?'Shoot Mode':'START SHOOT'}</button><button class="secondary" onclick="openShotItemForm('${p.id}')">＋ Cadru</button></div></section>${cats.map(c=>shotCategoryHtml(p,c)).join('')}${!p.items.length?empty('Shotlist gol. Adaugă primul cadru.'):''}<div class="footer-actions"><button class="secondary" onclick="openShotProjectEdit('${p.id}')">Editează proiect</button><button class="primary" onclick="openWrapShoot('${p.id}')">WRAP SHOOT</button></div><button class="danger" style="width:100%;margin-top:10px" onclick="deleteShotProject('${p.id}')">Șterge proiectul</button>`}
function shotCategoryHtml(p,c){const items=p.items.filter(i=>i.category===c),done=items.filter(i=>i.checked).length;return `<section class="shot-category"><div class="shot-category-head"><h3>${escapeHtml(c)}</h3><span class="pill ${done===items.length?'ok':''}">${done}/${items.length}</span></div><div class="list">${items.map(i=>`<div class="item shot-row ${i.must?'must':''} ${i.checked?'done':''}" onclick="toggleShot('${p.id}','${i.id}')"><div class="checkbox ${i.checked?'checked':''}">${i.checked?'✓':''}</div><div class="item-left"><div class="item-title">${escapeHtml(i.text)}</div><div class="item-sub">${i.must?'MUST HAVE':'Cadru'}</div></div><div class="shot-tools"><button class="ghost tiny" onclick="event.stopPropagation();openShotItemForm('${p.id}','${i.id}')">Edit</button></div></div>`).join('')}</div></section>`}
function toggleShot(pid,iid){const p=byId(ensureShotlists().projects,pid),i=byId(p.items,iid);i.checked=!i.checked;save();renderShotlists()}
function startShoot(id){byId(ensureShotlists().projects,id).started=true;save();document.body.classList.add('shot-fullscreen');renderShotProject(id)}
function exitShootMode(){document.body.classList.remove('shot-fullscreen')}
function openShotItemForm(pid,iid=''){const p=byId(ensureShotlists().projects,pid),i=byId(p.items,iid)||{text:'',category:'B-ROLL',must:false};openModal(iid?'Editează cadru':'Adaugă cadru',`<div class="form-grid"><label>Cadru<input id="siText" value="${escapeHtml(i.text)}" placeholder="Slow shutter"></label><label>Categorie<select id="siCategory">${SHOT_CATEGORIES.map(c=>`<option ${c===i.category?'selected':''}>${c}</option>`).join('')}</select></label><label class="charge-check"><input id="siMust" type="checkbox" ${i.must?'checked':''}> MUST HAVE</label><button type="button" class="primary" onclick="saveShotItem('${pid}','${iid}')">Salvează</button>${iid?`<button type="button" class="danger" onclick="deleteShotItem('${pid}','${iid}')">Șterge cadrul</button>`:''}</div>`)}
function saveShotItem(pid,iid=''){const p=byId(ensureShotlists().projects,pid),payload={text:siText.value.trim(),category:siCategory.value,must:siMust.checked};if(!payload.text)return alert('Scrie cadrul.');if(iid)Object.assign(byId(p.items,iid),payload);else p.items.push({id:uid(),checked:false,...payload});save();modal.close();renderShotlists()}
function deleteShotItem(pid,iid){if(!confirm('Ștergi cadrul din shotlist?'))return;const p=byId(ensureShotlists().projects,pid);p.items=p.items.filter(i=>i.id!==iid);save();modal.close();renderShotlists()}
function openShotProjectEdit(id){const p=byId(ensureShotlists().projects,id);openModal('Editează proiect',`<div class="form-grid"><label>Nume<input id="speName" value="${escapeHtml(p.name)}"></label><label>Data<input id="speDate" type="date" value="${p.date}"></label><button type="button" class="primary" onclick="saveShotProjectEdit('${id}')">Salvează</button></div>`)}
function saveShotProjectEdit(id){const p=byId(ensureShotlists().projects,id);p.name=speName.value.trim()||p.name;p.date=speDate.value;save();modal.close();renderShotlists()}
function openWrapShoot(id){const p=byId(ensureShotlists().projects,id),labels=['Cardurile sunt în husă și numărate','Fișierele audio sunt salvate','Recorderele au fost oprite','Tot gear-ul este recuperat','Locația a fost verificată','Observațiile importante sunt notate','Material copiat pe SSD principal','A doua copie / backup realizat'];if(!p.wrapItems?.length)p.wrapItems=labels.map(text=>({id:uid(),text,checked:false}));openModal('WRAP SHOOT',`<div class="stack"><div class="row"><b>MUST HAVE</b><span class="pill ${p.items.filter(i=>i.must&&!i.checked).length?'warn':'ok'}">${p.items.filter(i=>i.must&&i.checked).length}/${p.items.filter(i=>i.must).length}</span></div>${p.items.some(i=>i.must&&!i.checked)?'<p class="charge-note">Mai lipsesc cadre esențiale. Poți încheia doar după confirmare.</p>':''}${p.wrapItems.map(w=>`<label class="item wrap-check"><input class="wrapBox" data-id="${w.id}" type="checkbox" ${w.checked?'checked':''}><span>${escapeHtml(w.text)}</span></label>`).join('')}<button type="button" class="primary" onclick="finishWrapShoot('${id}')">Finalizează filmarea</button></div>`)}
function finishWrapShoot(id){const p=byId(ensureShotlists().projects,id);document.querySelectorAll('.wrapBox').forEach(x=>{const w=byId(p.wrapItems,x.dataset.id);w.checked=x.checked});const missingMust=p.items.filter(i=>i.must&&!i.checked).length,missingWrap=p.wrapItems.filter(i=>!i.checked).length;if((missingMust||missingWrap)&&!confirm(`Mai sunt ${missingMust} MUST HAVE și ${missingWrap} verificări nebifate. Marchezi totuși filmarea finalizată?`))return;p.completed=true;p.completedAt=new Date().toISOString();save();modal.close();exitShootMode();currentShotId=null;renderShotlists()}
function deleteShotProject(id){if(!confirm('Ștergi proiectul și toate bifările lui?'))return;const d=ensureShotlists();d.projects=d.projects.filter(p=>p.id!==id);save();currentShotId=null;exitShootMode();renderShotlists()}
function openShotPresetForm(id=''){const d=ensureShotlists(),p=byId(d.presets,id)||{name:'',notes:'',items:[]};openModal(id?'Editează preset':'Preset nou',`<div class="form-grid"><label>Nume<input id="sprName" value="${escapeHtml(p.name)}"></label><label>Notițe<textarea id="sprNotes">${escapeHtml(p.notes||'')}</textarea></label><button type="button" class="primary" onclick="saveShotPreset('${id}')">Salvează numele și notițele</button>${id?`<div class="row"><b>Cadre (${p.items.length})</b><button type="button" class="secondary tiny" onclick="openShotPresetItemForm('${id}')">＋ Cadru</button></div><div class="list">${p.items.map(i=>`<div class="item"><div class="item-left"><div class="item-title">${escapeHtml(i.text)}</div><div class="item-sub">${escapeHtml(i.category)}${i.must?' · MUST HAVE':''}</div></div><button type="button" class="ghost tiny" onclick="openShotPresetItemForm('${id}','${i.id}')">Edit</button></div>`).join('')||'<p class="empty">Preset gol.</p>'}</div>`:''}</div>`)}
function saveShotPreset(id=''){const d=ensureShotlists(),payload={name:sprName.value.trim(),notes:sprNotes.value.trim()};if(!payload.name)return alert('Pune numele presetului.');if(id)Object.assign(byId(d.presets,id),payload);else d.presets.push({id:uid(),items:[shot('Slow Shutter','CREATIVE')],...payload});save();modal.close();renderShotlists()}
function openShotPresetItemForm(pid,iid=''){const p=byId(ensureShotlists().presets,pid),i=byId(p.items,iid)||{text:'',category:'B-ROLL',must:false};openModal(iid?'Editează cadrul din preset':'Cadru nou în preset',`<div class="form-grid"><label>Cadru<input id="spiText" value="${escapeHtml(i.text)}"></label><label>Categorie<select id="spiCategory">${SHOT_CATEGORIES.map(c=>`<option ${c===i.category?'selected':''}>${c}</option>`).join('')}</select></label><label class="charge-check"><input id="spiMust" type="checkbox" ${i.must?'checked':''}> MUST HAVE</label><button type="button" class="primary" onclick="saveShotPresetItem('${pid}','${iid}')">Salvează</button>${iid?`<button type="button" class="danger" onclick="deleteShotPresetItem('${pid}','${iid}')">Șterge cadrul</button>`:''}</div>`)}
function saveShotPresetItem(pid,iid=''){const p=byId(ensureShotlists().presets,pid),payload={text:spiText.value.trim(),category:spiCategory.value,must:spiMust.checked};if(!payload.text)return alert('Scrie cadrul.');if(iid)Object.assign(byId(p.items,iid),payload);else p.items.push({id:uid(),checked:false,...payload});save();openShotPresetForm(pid)}
function deleteShotPresetItem(pid,iid){if(!confirm('Ștergi cadrul din preset?'))return;const p=byId(ensureShotlists().presets,pid);p.items=p.items.filter(i=>i.id!==iid);save();openShotPresetForm(pid)}
function deleteShotPreset(id){if(!confirm('Ștergi presetul? Proiectele deja create rămân intacte.'))return;const d=ensureShotlists();d.presets=d.presets.filter(p=>p.id!==id);save();renderShotlists()}
